package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class DGTL_GTW_MAPPING_DETAILSVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_GTW_MAPPING_DETAILS.MAPPING_ID
     */
    private String MAPPING_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_MAPPING_DETAILS.SOURCE_KEY
     */
    private String SOURCE_KEY;

    /**
     * This field corresponds to the database column DGTL_GTW_MAPPING_DETAILS.DESTINATION_KEY
     */
    private String DESTINATION_KEY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_MAPPING_DETAILS.MAPPING_ID
     *
     * @return the value of DGTL_GTW_MAPPING_DETAILS.MAPPING_ID
     */
    public String getMAPPING_ID() {
        return MAPPING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_MAPPING_DETAILS.MAPPING_ID
     *
     * @param MAPPING_ID the value for DGTL_GTW_MAPPING_DETAILS.MAPPING_ID
     */
    public void setMAPPING_ID(String MAPPING_ID) {
        this.MAPPING_ID = MAPPING_ID == null ? null : MAPPING_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_MAPPING_DETAILS.SOURCE_KEY
     *
     * @return the value of DGTL_GTW_MAPPING_DETAILS.SOURCE_KEY
     */
    public String getSOURCE_KEY() {
        return SOURCE_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_MAPPING_DETAILS.SOURCE_KEY
     *
     * @param SOURCE_KEY the value for DGTL_GTW_MAPPING_DETAILS.SOURCE_KEY
     */
    public void setSOURCE_KEY(String SOURCE_KEY) {
        this.SOURCE_KEY = SOURCE_KEY == null ? null : SOURCE_KEY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_MAPPING_DETAILS.DESTINATION_KEY
     *
     * @return the value of DGTL_GTW_MAPPING_DETAILS.DESTINATION_KEY
     */
    public String getDESTINATION_KEY() {
        return DESTINATION_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_MAPPING_DETAILS.DESTINATION_KEY
     *
     * @param DESTINATION_KEY the value for DGTL_GTW_MAPPING_DETAILS.DESTINATION_KEY
     */
    public void setDESTINATION_KEY(String DESTINATION_KEY) {
        this.DESTINATION_KEY = DESTINATION_KEY == null ? null : DESTINATION_KEY.trim();
    }
}