package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DGTL_ISO_SUB_FLDSVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_ISO_SUB_FLDS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_SUB_FLDS.FIELD_NO
     */
    private BigDecimal FIELD_NO;

    /**
     * This field corresponds to the database column DGTL_ISO_SUB_FLDS.INT_CODE
     */
    private BigDecimal INT_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_SUB_FLDS.SUB_FLD_CODE
     */
    private BigDecimal SUB_FLD_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_SUB_FLDS.SUB_FLD_NAME
     */
    private String SUB_FLD_NAME;

    /**
     * This field corresponds to the database column DGTL_ISO_SUB_FLDS.SUB_FLD_TYPE
     */
    private String SUB_FLD_TYPE;

    /**
     * This field corresponds to the database column DGTL_ISO_SUB_FLDS.SUB_FLD_LENGTH
     */
    private BigDecimal SUB_FLD_LENGTH;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_SUB_FLDS.COMP_CODE
     *
     * @return the value of DGTL_ISO_SUB_FLDS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_SUB_FLDS.COMP_CODE
     *
     * @param COMP_CODE the value for DGTL_ISO_SUB_FLDS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_SUB_FLDS.FIELD_NO
     *
     * @return the value of DGTL_ISO_SUB_FLDS.FIELD_NO
     */
    public BigDecimal getFIELD_NO() {
        return FIELD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_SUB_FLDS.FIELD_NO
     *
     * @param FIELD_NO the value for DGTL_ISO_SUB_FLDS.FIELD_NO
     */
    public void setFIELD_NO(BigDecimal FIELD_NO) {
        this.FIELD_NO = FIELD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_SUB_FLDS.INT_CODE
     *
     * @return the value of DGTL_ISO_SUB_FLDS.INT_CODE
     */
    public BigDecimal getINT_CODE() {
        return INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_SUB_FLDS.INT_CODE
     *
     * @param INT_CODE the value for DGTL_ISO_SUB_FLDS.INT_CODE
     */
    public void setINT_CODE(BigDecimal INT_CODE) {
        this.INT_CODE = INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_CODE
     *
     * @return the value of DGTL_ISO_SUB_FLDS.SUB_FLD_CODE
     */
    public BigDecimal getSUB_FLD_CODE() {
        return SUB_FLD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_CODE
     *
     * @param SUB_FLD_CODE the value for DGTL_ISO_SUB_FLDS.SUB_FLD_CODE
     */
    public void setSUB_FLD_CODE(BigDecimal SUB_FLD_CODE) {
        this.SUB_FLD_CODE = SUB_FLD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_NAME
     *
     * @return the value of DGTL_ISO_SUB_FLDS.SUB_FLD_NAME
     */
    public String getSUB_FLD_NAME() {
        return SUB_FLD_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_NAME
     *
     * @param SUB_FLD_NAME the value for DGTL_ISO_SUB_FLDS.SUB_FLD_NAME
     */
    public void setSUB_FLD_NAME(String SUB_FLD_NAME) {
        this.SUB_FLD_NAME = SUB_FLD_NAME == null ? null : SUB_FLD_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_TYPE
     *
     * @return the value of DGTL_ISO_SUB_FLDS.SUB_FLD_TYPE
     */
    public String getSUB_FLD_TYPE() {
        return SUB_FLD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_TYPE
     *
     * @param SUB_FLD_TYPE the value for DGTL_ISO_SUB_FLDS.SUB_FLD_TYPE
     */
    public void setSUB_FLD_TYPE(String SUB_FLD_TYPE) {
        this.SUB_FLD_TYPE = SUB_FLD_TYPE == null ? null : SUB_FLD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_LENGTH
     *
     * @return the value of DGTL_ISO_SUB_FLDS.SUB_FLD_LENGTH
     */
    public BigDecimal getSUB_FLD_LENGTH() {
        return SUB_FLD_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_SUB_FLDS.SUB_FLD_LENGTH
     *
     * @param SUB_FLD_LENGTH the value for DGTL_ISO_SUB_FLDS.SUB_FLD_LENGTH
     */
    public void setSUB_FLD_LENGTH(BigDecimal SUB_FLD_LENGTH) {
        this.SUB_FLD_LENGTH = SUB_FLD_LENGTH;
    }
}