package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DGTL_ISO_MSGSVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.INT_CODE
     */
    private BigDecimal INT_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.MESSAGE_CODE
     */
    private BigDecimal MESSAGE_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.REQUEST_MTI
     */
    private String REQUEST_MTI;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.REQUEST_BITMAP1
     */
    private String REQUEST_BITMAP1;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.REQUEST_BITMAP2
     */
    private String REQUEST_BITMAP2;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.REQUEST_DESCRIPTION
     */
    private String REQUEST_DESCRIPTION;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.RESPONSE_MTI
     */
    private String RESPONSE_MTI;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.RESPONSE_BITMAP1
     */
    private String RESPONSE_BITMAP1;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.RESPONSE_BITMAP2
     */
    private String RESPONSE_BITMAP2;

    /**
     * This field corresponds to the database column DGTL_ISO_MSGS.RESPONSE_DESCRIPTION
     */
    private String RESPONSE_DESCRIPTION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.COMP_CODE
     *
     * @return the value of DGTL_ISO_MSGS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.COMP_CODE
     *
     * @param COMP_CODE the value for DGTL_ISO_MSGS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.INT_CODE
     *
     * @return the value of DGTL_ISO_MSGS.INT_CODE
     */
    public BigDecimal getINT_CODE() {
        return INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.INT_CODE
     *
     * @param INT_CODE the value for DGTL_ISO_MSGS.INT_CODE
     */
    public void setINT_CODE(BigDecimal INT_CODE) {
        this.INT_CODE = INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.MESSAGE_CODE
     *
     * @return the value of DGTL_ISO_MSGS.MESSAGE_CODE
     */
    public BigDecimal getMESSAGE_CODE() {
        return MESSAGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.MESSAGE_CODE
     *
     * @param MESSAGE_CODE the value for DGTL_ISO_MSGS.MESSAGE_CODE
     */
    public void setMESSAGE_CODE(BigDecimal MESSAGE_CODE) {
        this.MESSAGE_CODE = MESSAGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.REQUEST_MTI
     *
     * @return the value of DGTL_ISO_MSGS.REQUEST_MTI
     */
    public String getREQUEST_MTI() {
        return REQUEST_MTI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.REQUEST_MTI
     *
     * @param REQUEST_MTI the value for DGTL_ISO_MSGS.REQUEST_MTI
     */
    public void setREQUEST_MTI(String REQUEST_MTI) {
        this.REQUEST_MTI = REQUEST_MTI == null ? null : REQUEST_MTI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.REQUEST_BITMAP1
     *
     * @return the value of DGTL_ISO_MSGS.REQUEST_BITMAP1
     */
    public String getREQUEST_BITMAP1() {
        return REQUEST_BITMAP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.REQUEST_BITMAP1
     *
     * @param REQUEST_BITMAP1 the value for DGTL_ISO_MSGS.REQUEST_BITMAP1
     */
    public void setREQUEST_BITMAP1(String REQUEST_BITMAP1) {
        this.REQUEST_BITMAP1 = REQUEST_BITMAP1 == null ? null : REQUEST_BITMAP1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.REQUEST_BITMAP2
     *
     * @return the value of DGTL_ISO_MSGS.REQUEST_BITMAP2
     */
    public String getREQUEST_BITMAP2() {
        return REQUEST_BITMAP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.REQUEST_BITMAP2
     *
     * @param REQUEST_BITMAP2 the value for DGTL_ISO_MSGS.REQUEST_BITMAP2
     */
    public void setREQUEST_BITMAP2(String REQUEST_BITMAP2) {
        this.REQUEST_BITMAP2 = REQUEST_BITMAP2 == null ? null : REQUEST_BITMAP2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.REQUEST_DESCRIPTION
     *
     * @return the value of DGTL_ISO_MSGS.REQUEST_DESCRIPTION
     */
    public String getREQUEST_DESCRIPTION() {
        return REQUEST_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.REQUEST_DESCRIPTION
     *
     * @param REQUEST_DESCRIPTION the value for DGTL_ISO_MSGS.REQUEST_DESCRIPTION
     */
    public void setREQUEST_DESCRIPTION(String REQUEST_DESCRIPTION) {
        this.REQUEST_DESCRIPTION = REQUEST_DESCRIPTION == null ? null : REQUEST_DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.RESPONSE_MTI
     *
     * @return the value of DGTL_ISO_MSGS.RESPONSE_MTI
     */
    public String getRESPONSE_MTI() {
        return RESPONSE_MTI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.RESPONSE_MTI
     *
     * @param RESPONSE_MTI the value for DGTL_ISO_MSGS.RESPONSE_MTI
     */
    public void setRESPONSE_MTI(String RESPONSE_MTI) {
        this.RESPONSE_MTI = RESPONSE_MTI == null ? null : RESPONSE_MTI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.RESPONSE_BITMAP1
     *
     * @return the value of DGTL_ISO_MSGS.RESPONSE_BITMAP1
     */
    public String getRESPONSE_BITMAP1() {
        return RESPONSE_BITMAP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.RESPONSE_BITMAP1
     *
     * @param RESPONSE_BITMAP1 the value for DGTL_ISO_MSGS.RESPONSE_BITMAP1
     */
    public void setRESPONSE_BITMAP1(String RESPONSE_BITMAP1) {
        this.RESPONSE_BITMAP1 = RESPONSE_BITMAP1 == null ? null : RESPONSE_BITMAP1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.RESPONSE_BITMAP2
     *
     * @return the value of DGTL_ISO_MSGS.RESPONSE_BITMAP2
     */
    public String getRESPONSE_BITMAP2() {
        return RESPONSE_BITMAP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.RESPONSE_BITMAP2
     *
     * @param RESPONSE_BITMAP2 the value for DGTL_ISO_MSGS.RESPONSE_BITMAP2
     */
    public void setRESPONSE_BITMAP2(String RESPONSE_BITMAP2) {
        this.RESPONSE_BITMAP2 = RESPONSE_BITMAP2 == null ? null : RESPONSE_BITMAP2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_MSGS.RESPONSE_DESCRIPTION
     *
     * @return the value of DGTL_ISO_MSGS.RESPONSE_DESCRIPTION
     */
    public String getRESPONSE_DESCRIPTION() {
        return RESPONSE_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_MSGS.RESPONSE_DESCRIPTION
     *
     * @param RESPONSE_DESCRIPTION the value for DGTL_ISO_MSGS.RESPONSE_DESCRIPTION
     */
    public void setRESPONSE_DESCRIPTION(String RESPONSE_DESCRIPTION) {
        this.RESPONSE_DESCRIPTION = RESPONSE_DESCRIPTION == null ? null : RESPONSE_DESCRIPTION.trim();
    }
}