package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class DGTL_GTW_MAPPINGVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_GTW_MAPPING.MAPPING_ID
     */
    private String MAPPING_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_MAPPING.WS_NAME
     */
    private String WS_NAME;

    /**
     * This field corresponds to the database column DGTL_GTW_MAPPING.OPER_NAME
     */
    private String OPER_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_MAPPING.MAPPING_ID
     *
     * @return the value of DGTL_GTW_MAPPING.MAPPING_ID
     */
    public String getMAPPING_ID() {
        return MAPPING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_MAPPING.MAPPING_ID
     *
     * @param MAPPING_ID the value for DGTL_GTW_MAPPING.MAPPING_ID
     */
    public void setMAPPING_ID(String MAPPING_ID) {
        this.MAPPING_ID = MAPPING_ID == null ? null : MAPPING_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_MAPPING.WS_NAME
     *
     * @return the value of DGTL_GTW_MAPPING.WS_NAME
     */
    public String getWS_NAME() {
        return WS_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_MAPPING.WS_NAME
     *
     * @param WS_NAME the value for DGTL_GTW_MAPPING.WS_NAME
     */
    public void setWS_NAME(String WS_NAME) {
        this.WS_NAME = WS_NAME == null ? null : WS_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_MAPPING.OPER_NAME
     *
     * @return the value of DGTL_GTW_MAPPING.OPER_NAME
     */
    public String getOPER_NAME() {
        return OPER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_MAPPING.OPER_NAME
     *
     * @param OPER_NAME the value for DGTL_GTW_MAPPING.OPER_NAME
     */
    public void setOPER_NAME(String OPER_NAME) {
        this.OPER_NAME = OPER_NAME == null ? null : OPER_NAME.trim();
    }
}