package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DGTL_ISO_FLDSVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.FIELD_NO
     */
    private BigDecimal FIELD_NO;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.INT_CODE
     */
    private BigDecimal INT_CODE;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.FIELD_NAME
     */
    private String FIELD_NAME;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.FIELD_LENGTH
     */
    private BigDecimal FIELD_LENGTH;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.FIELD_LENL
     */
    private BigDecimal FIELD_LENL;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.TOTAL_MASK
     */
    private BigDecimal TOTAL_MASK;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.PARTIAL_MASK
     */
    private String PARTIAL_MASK;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.FIELD_TYPE
     */
    private String FIELD_TYPE;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.IS_DECIMAL_YN
     */
    private String IS_DECIMAL_YN;

    /**
     * This field corresponds to the database column DGTL_ISO_FLDS.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.COMP_CODE
     *
     * @return the value of DGTL_ISO_FLDS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.COMP_CODE
     *
     * @param COMP_CODE the value for DGTL_ISO_FLDS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.FIELD_NO
     *
     * @return the value of DGTL_ISO_FLDS.FIELD_NO
     */
    public BigDecimal getFIELD_NO() {
        return FIELD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.FIELD_NO
     *
     * @param FIELD_NO the value for DGTL_ISO_FLDS.FIELD_NO
     */
    public void setFIELD_NO(BigDecimal FIELD_NO) {
        this.FIELD_NO = FIELD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.INT_CODE
     *
     * @return the value of DGTL_ISO_FLDS.INT_CODE
     */
    public BigDecimal getINT_CODE() {
        return INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.INT_CODE
     *
     * @param INT_CODE the value for DGTL_ISO_FLDS.INT_CODE
     */
    public void setINT_CODE(BigDecimal INT_CODE) {
        this.INT_CODE = INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.FIELD_NAME
     *
     * @return the value of DGTL_ISO_FLDS.FIELD_NAME
     */
    public String getFIELD_NAME() {
        return FIELD_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.FIELD_NAME
     *
     * @param FIELD_NAME the value for DGTL_ISO_FLDS.FIELD_NAME
     */
    public void setFIELD_NAME(String FIELD_NAME) {
        this.FIELD_NAME = FIELD_NAME == null ? null : FIELD_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.FIELD_LENGTH
     *
     * @return the value of DGTL_ISO_FLDS.FIELD_LENGTH
     */
    public BigDecimal getFIELD_LENGTH() {
        return FIELD_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.FIELD_LENGTH
     *
     * @param FIELD_LENGTH the value for DGTL_ISO_FLDS.FIELD_LENGTH
     */
    public void setFIELD_LENGTH(BigDecimal FIELD_LENGTH) {
        this.FIELD_LENGTH = FIELD_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.FIELD_LENL
     *
     * @return the value of DGTL_ISO_FLDS.FIELD_LENL
     */
    public BigDecimal getFIELD_LENL() {
        return FIELD_LENL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.FIELD_LENL
     *
     * @param FIELD_LENL the value for DGTL_ISO_FLDS.FIELD_LENL
     */
    public void setFIELD_LENL(BigDecimal FIELD_LENL) {
        this.FIELD_LENL = FIELD_LENL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.TOTAL_MASK
     *
     * @return the value of DGTL_ISO_FLDS.TOTAL_MASK
     */
    public BigDecimal getTOTAL_MASK() {
        return TOTAL_MASK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.TOTAL_MASK
     *
     * @param TOTAL_MASK the value for DGTL_ISO_FLDS.TOTAL_MASK
     */
    public void setTOTAL_MASK(BigDecimal TOTAL_MASK) {
        this.TOTAL_MASK = TOTAL_MASK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.PARTIAL_MASK
     *
     * @return the value of DGTL_ISO_FLDS.PARTIAL_MASK
     */
    public String getPARTIAL_MASK() {
        return PARTIAL_MASK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.PARTIAL_MASK
     *
     * @param PARTIAL_MASK the value for DGTL_ISO_FLDS.PARTIAL_MASK
     */
    public void setPARTIAL_MASK(String PARTIAL_MASK) {
        this.PARTIAL_MASK = PARTIAL_MASK == null ? null : PARTIAL_MASK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.FIELD_TYPE
     *
     * @return the value of DGTL_ISO_FLDS.FIELD_TYPE
     */
    public String getFIELD_TYPE() {
        return FIELD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.FIELD_TYPE
     *
     * @param FIELD_TYPE the value for DGTL_ISO_FLDS.FIELD_TYPE
     */
    public void setFIELD_TYPE(String FIELD_TYPE) {
        this.FIELD_TYPE = FIELD_TYPE == null ? null : FIELD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.IS_DECIMAL_YN
     *
     * @return the value of DGTL_ISO_FLDS.IS_DECIMAL_YN
     */
    public String getIS_DECIMAL_YN() {
        return IS_DECIMAL_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.IS_DECIMAL_YN
     *
     * @param IS_DECIMAL_YN the value for DGTL_ISO_FLDS.IS_DECIMAL_YN
     */
    public void setIS_DECIMAL_YN(String IS_DECIMAL_YN) {
        this.IS_DECIMAL_YN = IS_DECIMAL_YN == null ? null : IS_DECIMAL_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_ISO_FLDS.EXPRESSION
     *
     * @return the value of DGTL_ISO_FLDS.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_ISO_FLDS.EXPRESSION
     *
     * @param EXPRESSION the value for DGTL_ISO_FLDS.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }
}