package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IM_API_USERSVO extends BaseVO {
    /**
     * This field corresponds to the database column IM_API_USERS.API_CODE
     */
    private BigDecimal API_CODE;

    /**
     * This field corresponds to the database column IM_API_USERS.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_API_USERS.API_CODE
     *
     * @return the value of IM_API_USERS.API_CODE
     */
    public BigDecimal getAPI_CODE() {
        return API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_API_USERS.API_CODE
     *
     * @param API_CODE the value for IM_API_USERS.API_CODE
     */
    public void setAPI_CODE(BigDecimal API_CODE) {
        this.API_CODE = API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_API_USERS.USER_ID
     *
     * @return the value of IM_API_USERS.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_API_USERS.USER_ID
     *
     * @param USER_ID the value for IM_API_USERS.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}