package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IM_API_MACHINEVO extends BaseVO {
    /**
     * This field corresponds to the database column IM_API_MACHINE.API_CODE
     */
    private BigDecimal API_CODE;

    /**
     * This field corresponds to the database column IM_API_MACHINE.MACHINE_NAME
     */
    private String MACHINE_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_API_MACHINE.API_CODE
     *
     * @return the value of IM_API_MACHINE.API_CODE
     */
    public BigDecimal getAPI_CODE() {
        return API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_API_MACHINE.API_CODE
     *
     * @param API_CODE the value for IM_API_MACHINE.API_CODE
     */
    public void setAPI_CODE(BigDecimal API_CODE) {
        this.API_CODE = API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_API_MACHINE.MACHINE_NAME
     *
     * @return the value of IM_API_MACHINE.MACHINE_NAME
     */
    public String getMACHINE_NAME() {
        return MACHINE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_API_MACHINE.MACHINE_NAME
     *
     * @param MACHINE_NAME the value for IM_API_MACHINE.MACHINE_NAME
     */
    public void setMACHINE_NAME(String MACHINE_NAME) {
        this.MACHINE_NAME = MACHINE_NAME == null ? null : MACHINE_NAME.trim();
    }
}