package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IMCO_DYN_FILE_STRUCTUREVO extends BaseVO {
    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.FILE_STRUCTURE_ID
     */
    private BigDecimal FILE_STRUCTURE_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.REFERENCE
     */
    private String REFERENCE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.FILE_TYPE
     */
    private String FILE_TYPE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.EXTRACTION_CRITERIA
     */
    private String EXTRACTION_CRITERIA;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.DELIMITER
     */
    private String DELIMITER;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.JOB_ID
     */
    private BigDecimal JOB_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_STRUCTURE.FILE_SAMPLE
     */
    private String FILE_SAMPLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.FILE_STRUCTURE_ID
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.FILE_STRUCTURE_ID
     */
    public BigDecimal getFILE_STRUCTURE_ID() {
        return FILE_STRUCTURE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.FILE_STRUCTURE_ID
     *
     * @param FILE_STRUCTURE_ID the value for IMCO_DYN_FILE_STRUCTURE.FILE_STRUCTURE_ID
     */
    public void setFILE_STRUCTURE_ID(BigDecimal FILE_STRUCTURE_ID) {
        this.FILE_STRUCTURE_ID = FILE_STRUCTURE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.REFERENCE
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.REFERENCE
     */
    public String getREFERENCE() {
        return REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.REFERENCE
     *
     * @param REFERENCE the value for IMCO_DYN_FILE_STRUCTURE.REFERENCE
     */
    public void setREFERENCE(String REFERENCE) {
        this.REFERENCE = REFERENCE == null ? null : REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.FILE_TYPE
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.FILE_TYPE
     */
    public String getFILE_TYPE() {
        return FILE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.FILE_TYPE
     *
     * @param FILE_TYPE the value for IMCO_DYN_FILE_STRUCTURE.FILE_TYPE
     */
    public void setFILE_TYPE(String FILE_TYPE) {
        this.FILE_TYPE = FILE_TYPE == null ? null : FILE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.DESCRIPTION
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.DESCRIPTION
     *
     * @param DESCRIPTION the value for IMCO_DYN_FILE_STRUCTURE.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.EXTRACTION_CRITERIA
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.EXTRACTION_CRITERIA
     */
    public String getEXTRACTION_CRITERIA() {
        return EXTRACTION_CRITERIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.EXTRACTION_CRITERIA
     *
     * @param EXTRACTION_CRITERIA the value for IMCO_DYN_FILE_STRUCTURE.EXTRACTION_CRITERIA
     */
    public void setEXTRACTION_CRITERIA(String EXTRACTION_CRITERIA) {
        this.EXTRACTION_CRITERIA = EXTRACTION_CRITERIA == null ? null : EXTRACTION_CRITERIA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.DELIMITER
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.DELIMITER
     */
    public String getDELIMITER() {
        return DELIMITER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.DELIMITER
     *
     * @param DELIMITER the value for IMCO_DYN_FILE_STRUCTURE.DELIMITER
     */
    public void setDELIMITER(String DELIMITER) {
        this.DELIMITER = DELIMITER == null ? null : DELIMITER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.STATUS
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.STATUS
     *
     * @param STATUS the value for IMCO_DYN_FILE_STRUCTURE.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.CREATED_BY
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.CREATED_BY
     *
     * @param CREATED_BY the value for IMCO_DYN_FILE_STRUCTURE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.CREATED_DATE
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.CREATED_DATE
     *
     * @param CREATED_DATE the value for IMCO_DYN_FILE_STRUCTURE.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.MODIFIED_BY
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for IMCO_DYN_FILE_STRUCTURE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.MODIFIED_DATE
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for IMCO_DYN_FILE_STRUCTURE.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.DELETED_BY
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.DELETED_BY
     *
     * @param DELETED_BY the value for IMCO_DYN_FILE_STRUCTURE.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.DELETED_DATE
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.DELETED_DATE
     *
     * @param DELETED_DATE the value for IMCO_DYN_FILE_STRUCTURE.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.JOB_ID
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.JOB_ID
     */
    public BigDecimal getJOB_ID() {
        return JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.JOB_ID
     *
     * @param JOB_ID the value for IMCO_DYN_FILE_STRUCTURE.JOB_ID
     */
    public void setJOB_ID(BigDecimal JOB_ID) {
        this.JOB_ID = JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_STRUCTURE.FILE_SAMPLE
     *
     * @return the value of IMCO_DYN_FILE_STRUCTURE.FILE_SAMPLE
     */
    public String getFILE_SAMPLE() {
        return FILE_SAMPLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_STRUCTURE.FILE_SAMPLE
     *
     * @param FILE_SAMPLE the value for IMCO_DYN_FILE_STRUCTURE.FILE_SAMPLE
     */
    public void setFILE_SAMPLE(String FILE_SAMPLE) {
        this.FILE_SAMPLE = FILE_SAMPLE == null ? null : FILE_SAMPLE.trim();
    }
}