package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IMCO_DYN_FILE_TAGVO extends BaseVO {
    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.TAGS_ID
     */
    private BigDecimal TAGS_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.MESSAGE_ID
     */
    private BigDecimal MESSAGE_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.JOB_ID
     */
    private BigDecimal JOB_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.JOB_TYPE
     */
    private String JOB_TYPE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.INDEX_NO
     */
    private BigDecimal INDEX_NO;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.START_POS
     */
    private BigDecimal START_POS;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.TAG_NAME
     */
    private String TAG_NAME;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.TAG_VALUE
     */
    private String TAG_VALUE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.TAG_LENGTH
     */
    private BigDecimal TAG_LENGTH;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.PARENT_PATH
     */
    private String PARENT_PATH;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.IS_MULTIPLE_YN
     */
    private String IS_MULTIPLE_YN;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.IS_ATTR_YN
     */
    private String IS_ATTR_YN;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.TAG_COLOR
     */
    private String TAG_COLOR;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.DATA_TYPE
     */
    private String DATA_TYPE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_TAG.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.TAGS_ID
     *
     * @return the value of IMCO_DYN_FILE_TAG.TAGS_ID
     */
    public BigDecimal getTAGS_ID() {
        return TAGS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.TAGS_ID
     *
     * @param TAGS_ID the value for IMCO_DYN_FILE_TAG.TAGS_ID
     */
    public void setTAGS_ID(BigDecimal TAGS_ID) {
        this.TAGS_ID = TAGS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.MESSAGE_ID
     *
     * @return the value of IMCO_DYN_FILE_TAG.MESSAGE_ID
     */
    public BigDecimal getMESSAGE_ID() {
        return MESSAGE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.MESSAGE_ID
     *
     * @param MESSAGE_ID the value for IMCO_DYN_FILE_TAG.MESSAGE_ID
     */
    public void setMESSAGE_ID(BigDecimal MESSAGE_ID) {
        this.MESSAGE_ID = MESSAGE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.JOB_ID
     *
     * @return the value of IMCO_DYN_FILE_TAG.JOB_ID
     */
    public BigDecimal getJOB_ID() {
        return JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.JOB_ID
     *
     * @param JOB_ID the value for IMCO_DYN_FILE_TAG.JOB_ID
     */
    public void setJOB_ID(BigDecimal JOB_ID) {
        this.JOB_ID = JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.JOB_TYPE
     *
     * @return the value of IMCO_DYN_FILE_TAG.JOB_TYPE
     */
    public String getJOB_TYPE() {
        return JOB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.JOB_TYPE
     *
     * @param JOB_TYPE the value for IMCO_DYN_FILE_TAG.JOB_TYPE
     */
    public void setJOB_TYPE(String JOB_TYPE) {
        this.JOB_TYPE = JOB_TYPE == null ? null : JOB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.INDEX_NO
     *
     * @return the value of IMCO_DYN_FILE_TAG.INDEX_NO
     */
    public BigDecimal getINDEX_NO() {
        return INDEX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.INDEX_NO
     *
     * @param INDEX_NO the value for IMCO_DYN_FILE_TAG.INDEX_NO
     */
    public void setINDEX_NO(BigDecimal INDEX_NO) {
        this.INDEX_NO = INDEX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.START_POS
     *
     * @return the value of IMCO_DYN_FILE_TAG.START_POS
     */
    public BigDecimal getSTART_POS() {
        return START_POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.START_POS
     *
     * @param START_POS the value for IMCO_DYN_FILE_TAG.START_POS
     */
    public void setSTART_POS(BigDecimal START_POS) {
        this.START_POS = START_POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.TAG_NAME
     *
     * @return the value of IMCO_DYN_FILE_TAG.TAG_NAME
     */
    public String getTAG_NAME() {
        return TAG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.TAG_NAME
     *
     * @param TAG_NAME the value for IMCO_DYN_FILE_TAG.TAG_NAME
     */
    public void setTAG_NAME(String TAG_NAME) {
        this.TAG_NAME = TAG_NAME == null ? null : TAG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.TAG_VALUE
     *
     * @return the value of IMCO_DYN_FILE_TAG.TAG_VALUE
     */
    public String getTAG_VALUE() {
        return TAG_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.TAG_VALUE
     *
     * @param TAG_VALUE the value for IMCO_DYN_FILE_TAG.TAG_VALUE
     */
    public void setTAG_VALUE(String TAG_VALUE) {
        this.TAG_VALUE = TAG_VALUE == null ? null : TAG_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.TAG_LENGTH
     *
     * @return the value of IMCO_DYN_FILE_TAG.TAG_LENGTH
     */
    public BigDecimal getTAG_LENGTH() {
        return TAG_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.TAG_LENGTH
     *
     * @param TAG_LENGTH the value for IMCO_DYN_FILE_TAG.TAG_LENGTH
     */
    public void setTAG_LENGTH(BigDecimal TAG_LENGTH) {
        this.TAG_LENGTH = TAG_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.PARENT_PATH
     *
     * @return the value of IMCO_DYN_FILE_TAG.PARENT_PATH
     */
    public String getPARENT_PATH() {
        return PARENT_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.PARENT_PATH
     *
     * @param PARENT_PATH the value for IMCO_DYN_FILE_TAG.PARENT_PATH
     */
    public void setPARENT_PATH(String PARENT_PATH) {
        this.PARENT_PATH = PARENT_PATH == null ? null : PARENT_PATH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.IS_MULTIPLE_YN
     *
     * @return the value of IMCO_DYN_FILE_TAG.IS_MULTIPLE_YN
     */
    public String getIS_MULTIPLE_YN() {
        return IS_MULTIPLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.IS_MULTIPLE_YN
     *
     * @param IS_MULTIPLE_YN the value for IMCO_DYN_FILE_TAG.IS_MULTIPLE_YN
     */
    public void setIS_MULTIPLE_YN(String IS_MULTIPLE_YN) {
        this.IS_MULTIPLE_YN = IS_MULTIPLE_YN == null ? null : IS_MULTIPLE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.IS_ATTR_YN
     *
     * @return the value of IMCO_DYN_FILE_TAG.IS_ATTR_YN
     */
    public String getIS_ATTR_YN() {
        return IS_ATTR_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.IS_ATTR_YN
     *
     * @param IS_ATTR_YN the value for IMCO_DYN_FILE_TAG.IS_ATTR_YN
     */
    public void setIS_ATTR_YN(String IS_ATTR_YN) {
        this.IS_ATTR_YN = IS_ATTR_YN == null ? null : IS_ATTR_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.TAG_COLOR
     *
     * @return the value of IMCO_DYN_FILE_TAG.TAG_COLOR
     */
    public String getTAG_COLOR() {
        return TAG_COLOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.TAG_COLOR
     *
     * @param TAG_COLOR the value for IMCO_DYN_FILE_TAG.TAG_COLOR
     */
    public void setTAG_COLOR(String TAG_COLOR) {
        this.TAG_COLOR = TAG_COLOR == null ? null : TAG_COLOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.EXPRESSION
     *
     * @return the value of IMCO_DYN_FILE_TAG.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.EXPRESSION
     *
     * @param EXPRESSION the value for IMCO_DYN_FILE_TAG.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.DATA_TYPE
     *
     * @return the value of IMCO_DYN_FILE_TAG.DATA_TYPE
     */
    public String getDATA_TYPE() {
        return DATA_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.DATA_TYPE
     *
     * @param DATA_TYPE the value for IMCO_DYN_FILE_TAG.DATA_TYPE
     */
    public void setDATA_TYPE(String DATA_TYPE) {
        this.DATA_TYPE = DATA_TYPE == null ? null : DATA_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.DESCRIPTION
     *
     * @return the value of IMCO_DYN_FILE_TAG.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.DESCRIPTION
     *
     * @param DESCRIPTION the value for IMCO_DYN_FILE_TAG.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.CREATED_BY
     *
     * @return the value of IMCO_DYN_FILE_TAG.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.CREATED_BY
     *
     * @param CREATED_BY the value for IMCO_DYN_FILE_TAG.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.CREATED_DATE
     *
     * @return the value of IMCO_DYN_FILE_TAG.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.CREATED_DATE
     *
     * @param CREATED_DATE the value for IMCO_DYN_FILE_TAG.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.MODIFIED_BY
     *
     * @return the value of IMCO_DYN_FILE_TAG.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for IMCO_DYN_FILE_TAG.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_TAG.MODIFIED_DATE
     *
     * @return the value of IMCO_DYN_FILE_TAG.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_TAG.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for IMCO_DYN_FILE_TAG.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}