package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class IMCO_DYN_FILE_MESSAGEVO extends BaseVO {
    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_ID
     */
    private BigDecimal MESSAGE_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.FILE_STRUCTURE_ID
     */
    private BigDecimal FILE_STRUCTURE_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.JOB_ID
     */
    private BigDecimal JOB_ID;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.JOB_TYPE
     */
    private String JOB_TYPE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.INDEX_NO
     */
    private BigDecimal INDEX_NO;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.START_POS
     */
    private BigDecimal START_POS;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.IDENTIFIER
     */
    private String IDENTIFIER;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.DELIMITER
     */
    private String DELIMITER;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.IDENTIFIER_COLOR
     */
    private String IDENTIFIER_COLOR;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_TYPE
     */
    private String MESSAGE_TYPE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_SAMPLE
     */
    private String MESSAGE_SAMPLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_ID
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.MESSAGE_ID
     */
    public BigDecimal getMESSAGE_ID() {
        return MESSAGE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_ID
     *
     * @param MESSAGE_ID the value for IMCO_DYN_FILE_MESSAGE.MESSAGE_ID
     */
    public void setMESSAGE_ID(BigDecimal MESSAGE_ID) {
        this.MESSAGE_ID = MESSAGE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.FILE_STRUCTURE_ID
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.FILE_STRUCTURE_ID
     */
    public BigDecimal getFILE_STRUCTURE_ID() {
        return FILE_STRUCTURE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.FILE_STRUCTURE_ID
     *
     * @param FILE_STRUCTURE_ID the value for IMCO_DYN_FILE_MESSAGE.FILE_STRUCTURE_ID
     */
    public void setFILE_STRUCTURE_ID(BigDecimal FILE_STRUCTURE_ID) {
        this.FILE_STRUCTURE_ID = FILE_STRUCTURE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.JOB_ID
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.JOB_ID
     */
    public BigDecimal getJOB_ID() {
        return JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.JOB_ID
     *
     * @param JOB_ID the value for IMCO_DYN_FILE_MESSAGE.JOB_ID
     */
    public void setJOB_ID(BigDecimal JOB_ID) {
        this.JOB_ID = JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.JOB_TYPE
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.JOB_TYPE
     */
    public String getJOB_TYPE() {
        return JOB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.JOB_TYPE
     *
     * @param JOB_TYPE the value for IMCO_DYN_FILE_MESSAGE.JOB_TYPE
     */
    public void setJOB_TYPE(String JOB_TYPE) {
        this.JOB_TYPE = JOB_TYPE == null ? null : JOB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.INDEX_NO
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.INDEX_NO
     */
    public BigDecimal getINDEX_NO() {
        return INDEX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.INDEX_NO
     *
     * @param INDEX_NO the value for IMCO_DYN_FILE_MESSAGE.INDEX_NO
     */
    public void setINDEX_NO(BigDecimal INDEX_NO) {
        this.INDEX_NO = INDEX_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.START_POS
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.START_POS
     */
    public BigDecimal getSTART_POS() {
        return START_POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.START_POS
     *
     * @param START_POS the value for IMCO_DYN_FILE_MESSAGE.START_POS
     */
    public void setSTART_POS(BigDecimal START_POS) {
        this.START_POS = START_POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.IDENTIFIER
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.IDENTIFIER
     */
    public String getIDENTIFIER() {
        return IDENTIFIER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.IDENTIFIER
     *
     * @param IDENTIFIER the value for IMCO_DYN_FILE_MESSAGE.IDENTIFIER
     */
    public void setIDENTIFIER(String IDENTIFIER) {
        this.IDENTIFIER = IDENTIFIER == null ? null : IDENTIFIER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.DESCRIPTION
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.DESCRIPTION
     *
     * @param DESCRIPTION the value for IMCO_DYN_FILE_MESSAGE.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.DELIMITER
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.DELIMITER
     */
    public String getDELIMITER() {
        return DELIMITER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.DELIMITER
     *
     * @param DELIMITER the value for IMCO_DYN_FILE_MESSAGE.DELIMITER
     */
    public void setDELIMITER(String DELIMITER) {
        this.DELIMITER = DELIMITER == null ? null : DELIMITER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.IDENTIFIER_COLOR
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.IDENTIFIER_COLOR
     */
    public String getIDENTIFIER_COLOR() {
        return IDENTIFIER_COLOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.IDENTIFIER_COLOR
     *
     * @param IDENTIFIER_COLOR the value for IMCO_DYN_FILE_MESSAGE.IDENTIFIER_COLOR
     */
    public void setIDENTIFIER_COLOR(String IDENTIFIER_COLOR) {
        this.IDENTIFIER_COLOR = IDENTIFIER_COLOR == null ? null : IDENTIFIER_COLOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.STATUS
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.STATUS
     *
     * @param STATUS the value for IMCO_DYN_FILE_MESSAGE.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_TYPE
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.MESSAGE_TYPE
     */
    public String getMESSAGE_TYPE() {
        return MESSAGE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_TYPE
     *
     * @param MESSAGE_TYPE the value for IMCO_DYN_FILE_MESSAGE.MESSAGE_TYPE
     */
    public void setMESSAGE_TYPE(String MESSAGE_TYPE) {
        this.MESSAGE_TYPE = MESSAGE_TYPE == null ? null : MESSAGE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.CREATED_BY
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.CREATED_BY
     *
     * @param CREATED_BY the value for IMCO_DYN_FILE_MESSAGE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.CREATED_DATE
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.CREATED_DATE
     *
     * @param CREATED_DATE the value for IMCO_DYN_FILE_MESSAGE.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.MODIFIED_BY
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for IMCO_DYN_FILE_MESSAGE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.MODIFIED_DATE
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for IMCO_DYN_FILE_MESSAGE.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.DELETED_BY
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.DELETED_BY
     *
     * @param DELETED_BY the value for IMCO_DYN_FILE_MESSAGE.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.DELETED_DATE
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.DELETED_DATE
     *
     * @param DELETED_DATE the value for IMCO_DYN_FILE_MESSAGE.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_SAMPLE
     *
     * @return the value of IMCO_DYN_FILE_MESSAGE.MESSAGE_SAMPLE
     */
    public String getMESSAGE_SAMPLE() {
        return MESSAGE_SAMPLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMCO_DYN_FILE_MESSAGE.MESSAGE_SAMPLE
     *
     * @param MESSAGE_SAMPLE the value for IMCO_DYN_FILE_MESSAGE.MESSAGE_SAMPLE
     */
    public void setMESSAGE_SAMPLE(String MESSAGE_SAMPLE) {
        this.MESSAGE_SAMPLE = MESSAGE_SAMPLE == null ? null : MESSAGE_SAMPLE.trim();
    }
}