package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ISO_INT_MSGSVO extends BaseVO {
    /**
     * This field corresponds to the database column ISO_INT_MSGS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.INT_CODE
     */
    private BigDecimal INT_CODE;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.MESSAGE_CODE
     */
    private BigDecimal MESSAGE_CODE;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.POS
     */
    private BigDecimal POS;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.HEADER_DATA
     */
    private String HEADER_DATA;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.FIELDS_BITMAP1
     */
    private String FIELDS_BITMAP1;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.FIELDS_BITMAP2
     */
    private String FIELDS_BITMAP2;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column ISO_INT_MSGS.MTI
     */
    private String MTI;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.COMP_CODE
     *
     * @return the value of ISO_INT_MSGS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.COMP_CODE
     *
     * @param COMP_CODE the value for ISO_INT_MSGS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.INT_CODE
     *
     * @return the value of ISO_INT_MSGS.INT_CODE
     */
    public BigDecimal getINT_CODE() {
        return INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.INT_CODE
     *
     * @param INT_CODE the value for ISO_INT_MSGS.INT_CODE
     */
    public void setINT_CODE(BigDecimal INT_CODE) {
        this.INT_CODE = INT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.MESSAGE_CODE
     *
     * @return the value of ISO_INT_MSGS.MESSAGE_CODE
     */
    public BigDecimal getMESSAGE_CODE() {
        return MESSAGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.MESSAGE_CODE
     *
     * @param MESSAGE_CODE the value for ISO_INT_MSGS.MESSAGE_CODE
     */
    public void setMESSAGE_CODE(BigDecimal MESSAGE_CODE) {
        this.MESSAGE_CODE = MESSAGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.POS
     *
     * @return the value of ISO_INT_MSGS.POS
     */
    public BigDecimal getPOS() {
        return POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.POS
     *
     * @param POS the value for ISO_INT_MSGS.POS
     */
    public void setPOS(BigDecimal POS) {
        this.POS = POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.HEADER_DATA
     *
     * @return the value of ISO_INT_MSGS.HEADER_DATA
     */
    public String getHEADER_DATA() {
        return HEADER_DATA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.HEADER_DATA
     *
     * @param HEADER_DATA the value for ISO_INT_MSGS.HEADER_DATA
     */
    public void setHEADER_DATA(String HEADER_DATA) {
        this.HEADER_DATA = HEADER_DATA == null ? null : HEADER_DATA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.FIELDS_BITMAP1
     *
     * @return the value of ISO_INT_MSGS.FIELDS_BITMAP1
     */
    public String getFIELDS_BITMAP1() {
        return FIELDS_BITMAP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.FIELDS_BITMAP1
     *
     * @param FIELDS_BITMAP1 the value for ISO_INT_MSGS.FIELDS_BITMAP1
     */
    public void setFIELDS_BITMAP1(String FIELDS_BITMAP1) {
        this.FIELDS_BITMAP1 = FIELDS_BITMAP1 == null ? null : FIELDS_BITMAP1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.FIELDS_BITMAP2
     *
     * @return the value of ISO_INT_MSGS.FIELDS_BITMAP2
     */
    public String getFIELDS_BITMAP2() {
        return FIELDS_BITMAP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.FIELDS_BITMAP2
     *
     * @param FIELDS_BITMAP2 the value for ISO_INT_MSGS.FIELDS_BITMAP2
     */
    public void setFIELDS_BITMAP2(String FIELDS_BITMAP2) {
        this.FIELDS_BITMAP2 = FIELDS_BITMAP2 == null ? null : FIELDS_BITMAP2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.DESCRIPTION
     *
     * @return the value of ISO_INT_MSGS.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.DESCRIPTION
     *
     * @param DESCRIPTION the value for ISO_INT_MSGS.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ISO_INT_MSGS.MTI
     *
     * @return the value of ISO_INT_MSGS.MTI
     */
    public String getMTI() {
        return MTI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ISO_INT_MSGS.MTI
     *
     * @param MTI the value for ISO_INT_MSGS.MTI
     */
    public void setMTI(String MTI) {
        this.MTI = MTI == null ? null : MTI.trim();
    }
}