package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYNC_CONNECTIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYNC_CONNECTION.BR_CODE
     */
    private BigDecimal BR_CODE;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.PROCESS
     */
    private String PROCESS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.BR_CODE
     *
     * @return the value of SYNC_CONNECTION.BR_CODE
     */
    public BigDecimal getBR_CODE() {
        return BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.BR_CODE
     *
     * @param BR_CODE the value for SYNC_CONNECTION.BR_CODE
     */
    public void setBR_CODE(BigDecimal BR_CODE) {
        this.BR_CODE = BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.PROCESS
     *
     * @return the value of SYNC_CONNECTION.PROCESS
     */
    public String getPROCESS() {
        return PROCESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.PROCESS
     *
     * @param PROCESS the value for SYNC_CONNECTION.PROCESS
     */
    public void setPROCESS(String PROCESS) {
        this.PROCESS = PROCESS == null ? null : PROCESS.trim();
    }
}