package com.path.dbmaps.vo;

public class SYNC_ENTITY_PARAMETERSVOWithBLOBs extends SYNC_ENTITY_PARAMETERSVO {
    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.SP_SPECIFICATIONS
     */
    private String SP_SPECIFICATIONS;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS
     */
    private String QUERY_SPECIFICATIONS;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS1
     */
    private String QUERY_SPECIFICATIONS1;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS2
     */
    private String QUERY_SPECIFICATIONS2;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS3
     */
    private String QUERY_SPECIFICATIONS3;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.CRITERIA
     */
    private String CRITERIA;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.TMP_COLUMNS
     */
    private String TMP_COLUMNS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.SP_SPECIFICATIONS
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.SP_SPECIFICATIONS
     */
    public String getSP_SPECIFICATIONS() {
        return SP_SPECIFICATIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.SP_SPECIFICATIONS
     *
     * @param SP_SPECIFICATIONS the value for SYNC_ENTITY_PARAMETERS.SP_SPECIFICATIONS
     */
    public void setSP_SPECIFICATIONS(String SP_SPECIFICATIONS) {
        this.SP_SPECIFICATIONS = SP_SPECIFICATIONS == null ? null : SP_SPECIFICATIONS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS
     */
    public String getQUERY_SPECIFICATIONS() {
        return QUERY_SPECIFICATIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS
     *
     * @param QUERY_SPECIFICATIONS the value for SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS
     */
    public void setQUERY_SPECIFICATIONS(String QUERY_SPECIFICATIONS) {
        this.QUERY_SPECIFICATIONS = QUERY_SPECIFICATIONS == null ? null : QUERY_SPECIFICATIONS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS1
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS1
     */
    public String getQUERY_SPECIFICATIONS1() {
        return QUERY_SPECIFICATIONS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS1
     *
     * @param QUERY_SPECIFICATIONS1 the value for SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS1
     */
    public void setQUERY_SPECIFICATIONS1(String QUERY_SPECIFICATIONS1) {
        this.QUERY_SPECIFICATIONS1 = QUERY_SPECIFICATIONS1 == null ? null : QUERY_SPECIFICATIONS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS2
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS2
     */
    public String getQUERY_SPECIFICATIONS2() {
        return QUERY_SPECIFICATIONS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS2
     *
     * @param QUERY_SPECIFICATIONS2 the value for SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS2
     */
    public void setQUERY_SPECIFICATIONS2(String QUERY_SPECIFICATIONS2) {
        this.QUERY_SPECIFICATIONS2 = QUERY_SPECIFICATIONS2 == null ? null : QUERY_SPECIFICATIONS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS3
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS3
     */
    public String getQUERY_SPECIFICATIONS3() {
        return QUERY_SPECIFICATIONS3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS3
     *
     * @param QUERY_SPECIFICATIONS3 the value for SYNC_ENTITY_PARAMETERS.QUERY_SPECIFICATIONS3
     */
    public void setQUERY_SPECIFICATIONS3(String QUERY_SPECIFICATIONS3) {
        this.QUERY_SPECIFICATIONS3 = QUERY_SPECIFICATIONS3 == null ? null : QUERY_SPECIFICATIONS3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.CRITERIA
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.CRITERIA
     */
    public String getCRITERIA() {
        return CRITERIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.CRITERIA
     *
     * @param CRITERIA the value for SYNC_ENTITY_PARAMETERS.CRITERIA
     */
    public void setCRITERIA(String CRITERIA) {
        this.CRITERIA = CRITERIA == null ? null : CRITERIA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.TMP_COLUMNS
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.TMP_COLUMNS
     */
    public String getTMP_COLUMNS() {
        return TMP_COLUMNS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.TMP_COLUMNS
     *
     * @param TMP_COLUMNS the value for SYNC_ENTITY_PARAMETERS.TMP_COLUMNS
     */
    public void setTMP_COLUMNS(String TMP_COLUMNS) {
        this.TMP_COLUMNS = TMP_COLUMNS == null ? null : TMP_COLUMNS.trim();
    }
}