package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class SYNC_ENTITY_PARAMETERSVO extends SYNC_ENTITY_PARAMETERSVOKey {
    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.TO_BR
     */
    private BigDecimal TO_BR;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.REPL_TYPE
     */
    private BigDecimal REPL_TYPE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.REPL_DATETIME
     */
    private Date REPL_DATETIME;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.PERIOD
     */
    private BigDecimal PERIOD;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.PERIOD_TYPE
     */
    private String PERIOD_TYPE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.WHO_WINS
     */
    private String WHO_WINS;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ENABLE_TRIGGER
     */
    private String ENABLE_TRIGGER;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ENTITY_NAME
     */
    private String ENTITY_NAME;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.SP_NAME
     */
    private String SP_NAME;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.SYS_REPLICATION
     */
    private String SYS_REPLICATION;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ERR_SUSPENDED
     */
    private String ERR_SUSPENDED;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ERR_PERIOD
     */
    private BigDecimal ERR_PERIOD;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ERR_PERIOD_TYPE
     */
    private String ERR_PERIOD_TYPE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ERR_STOP_AFTER
     */
    private BigDecimal ERR_STOP_AFTER;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.PERIOD_DAY
     */
    private BigDecimal PERIOD_DAY;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.REPL_INSERT
     */
    private BigDecimal REPL_INSERT;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.REPL_UPDATE
     */
    private BigDecimal REPL_UPDATE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.REPL_DELETE
     */
    private BigDecimal REPL_DELETE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.POP_INSERT
     */
    private BigDecimal POP_INSERT;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.POP_UPDATE
     */
    private BigDecimal POP_UPDATE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.POP_DELETE
     */
    private BigDecimal POP_DELETE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.TIME_OUT
     */
    private BigDecimal TIME_OUT;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ADD_DATE1
     */
    private Date ADD_DATE1;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ADD_NUMBER1
     */
    private BigDecimal ADD_NUMBER1;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ADD_STRING1
     */
    private String ADD_STRING1;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.RELATIVE_FLAG
     */
    private BigDecimal RELATIVE_FLAG;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.INT_LEVEL
     */
    private String INT_LEVEL;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.EXT_SP_NAME
     */
    private String EXT_SP_NAME;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ENTITY_ORDER
     */
    private BigDecimal ENTITY_ORDER;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ERR_PROMPT
     */
    private BigDecimal ERR_PROMPT;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.ERR_TYPE
     */
    private BigDecimal ERR_TYPE;

    /**
     * This field corresponds to the database column SYNC_ENTITY_PARAMETERS.UPD_CNT_FLAG
     */
    private BigDecimal UPD_CNT_FLAG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.TO_BR
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.TO_BR
     */
    public BigDecimal getTO_BR() {
        return TO_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.TO_BR
     *
     * @param TO_BR the value for SYNC_ENTITY_PARAMETERS.TO_BR
     */
    public void setTO_BR(BigDecimal TO_BR) {
        this.TO_BR = TO_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.REPL_TYPE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.REPL_TYPE
     */
    public BigDecimal getREPL_TYPE() {
        return REPL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.REPL_TYPE
     *
     * @param REPL_TYPE the value for SYNC_ENTITY_PARAMETERS.REPL_TYPE
     */
    public void setREPL_TYPE(BigDecimal REPL_TYPE) {
        this.REPL_TYPE = REPL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.REPL_DATETIME
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.REPL_DATETIME
     */
    public Date getREPL_DATETIME() {
        return REPL_DATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.REPL_DATETIME
     *
     * @param REPL_DATETIME the value for SYNC_ENTITY_PARAMETERS.REPL_DATETIME
     */
    public void setREPL_DATETIME(Date REPL_DATETIME) {
        this.REPL_DATETIME = REPL_DATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.PERIOD
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.PERIOD
     */
    public BigDecimal getPERIOD() {
        return PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.PERIOD
     *
     * @param PERIOD the value for SYNC_ENTITY_PARAMETERS.PERIOD
     */
    public void setPERIOD(BigDecimal PERIOD) {
        this.PERIOD = PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.PERIOD_TYPE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.PERIOD_TYPE
     */
    public String getPERIOD_TYPE() {
        return PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.PERIOD_TYPE
     *
     * @param PERIOD_TYPE the value for SYNC_ENTITY_PARAMETERS.PERIOD_TYPE
     */
    public void setPERIOD_TYPE(String PERIOD_TYPE) {
        this.PERIOD_TYPE = PERIOD_TYPE == null ? null : PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.WHO_WINS
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.WHO_WINS
     */
    public String getWHO_WINS() {
        return WHO_WINS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.WHO_WINS
     *
     * @param WHO_WINS the value for SYNC_ENTITY_PARAMETERS.WHO_WINS
     */
    public void setWHO_WINS(String WHO_WINS) {
        this.WHO_WINS = WHO_WINS == null ? null : WHO_WINS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ENABLE_TRIGGER
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ENABLE_TRIGGER
     */
    public String getENABLE_TRIGGER() {
        return ENABLE_TRIGGER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ENABLE_TRIGGER
     *
     * @param ENABLE_TRIGGER the value for SYNC_ENTITY_PARAMETERS.ENABLE_TRIGGER
     */
    public void setENABLE_TRIGGER(String ENABLE_TRIGGER) {
        this.ENABLE_TRIGGER = ENABLE_TRIGGER == null ? null : ENABLE_TRIGGER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ENTITY_NAME
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ENTITY_NAME
     */
    public String getENTITY_NAME() {
        return ENTITY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ENTITY_NAME
     *
     * @param ENTITY_NAME the value for SYNC_ENTITY_PARAMETERS.ENTITY_NAME
     */
    public void setENTITY_NAME(String ENTITY_NAME) {
        this.ENTITY_NAME = ENTITY_NAME == null ? null : ENTITY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.SP_NAME
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.SP_NAME
     */
    public String getSP_NAME() {
        return SP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.SP_NAME
     *
     * @param SP_NAME the value for SYNC_ENTITY_PARAMETERS.SP_NAME
     */
    public void setSP_NAME(String SP_NAME) {
        this.SP_NAME = SP_NAME == null ? null : SP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ENTITY_TYPE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for SYNC_ENTITY_PARAMETERS.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.SYS_REPLICATION
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.SYS_REPLICATION
     */
    public String getSYS_REPLICATION() {
        return SYS_REPLICATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.SYS_REPLICATION
     *
     * @param SYS_REPLICATION the value for SYNC_ENTITY_PARAMETERS.SYS_REPLICATION
     */
    public void setSYS_REPLICATION(String SYS_REPLICATION) {
        this.SYS_REPLICATION = SYS_REPLICATION == null ? null : SYS_REPLICATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ERR_SUSPENDED
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ERR_SUSPENDED
     */
    public String getERR_SUSPENDED() {
        return ERR_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ERR_SUSPENDED
     *
     * @param ERR_SUSPENDED the value for SYNC_ENTITY_PARAMETERS.ERR_SUSPENDED
     */
    public void setERR_SUSPENDED(String ERR_SUSPENDED) {
        this.ERR_SUSPENDED = ERR_SUSPENDED == null ? null : ERR_SUSPENDED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ERR_PERIOD
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ERR_PERIOD
     */
    public BigDecimal getERR_PERIOD() {
        return ERR_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ERR_PERIOD
     *
     * @param ERR_PERIOD the value for SYNC_ENTITY_PARAMETERS.ERR_PERIOD
     */
    public void setERR_PERIOD(BigDecimal ERR_PERIOD) {
        this.ERR_PERIOD = ERR_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ERR_PERIOD_TYPE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ERR_PERIOD_TYPE
     */
    public String getERR_PERIOD_TYPE() {
        return ERR_PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ERR_PERIOD_TYPE
     *
     * @param ERR_PERIOD_TYPE the value for SYNC_ENTITY_PARAMETERS.ERR_PERIOD_TYPE
     */
    public void setERR_PERIOD_TYPE(String ERR_PERIOD_TYPE) {
        this.ERR_PERIOD_TYPE = ERR_PERIOD_TYPE == null ? null : ERR_PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ERR_STOP_AFTER
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ERR_STOP_AFTER
     */
    public BigDecimal getERR_STOP_AFTER() {
        return ERR_STOP_AFTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ERR_STOP_AFTER
     *
     * @param ERR_STOP_AFTER the value for SYNC_ENTITY_PARAMETERS.ERR_STOP_AFTER
     */
    public void setERR_STOP_AFTER(BigDecimal ERR_STOP_AFTER) {
        this.ERR_STOP_AFTER = ERR_STOP_AFTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.PERIOD_DAY
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.PERIOD_DAY
     */
    public BigDecimal getPERIOD_DAY() {
        return PERIOD_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.PERIOD_DAY
     *
     * @param PERIOD_DAY the value for SYNC_ENTITY_PARAMETERS.PERIOD_DAY
     */
    public void setPERIOD_DAY(BigDecimal PERIOD_DAY) {
        this.PERIOD_DAY = PERIOD_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.REPL_INSERT
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.REPL_INSERT
     */
    public BigDecimal getREPL_INSERT() {
        return REPL_INSERT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.REPL_INSERT
     *
     * @param REPL_INSERT the value for SYNC_ENTITY_PARAMETERS.REPL_INSERT
     */
    public void setREPL_INSERT(BigDecimal REPL_INSERT) {
        this.REPL_INSERT = REPL_INSERT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.REPL_UPDATE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.REPL_UPDATE
     */
    public BigDecimal getREPL_UPDATE() {
        return REPL_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.REPL_UPDATE
     *
     * @param REPL_UPDATE the value for SYNC_ENTITY_PARAMETERS.REPL_UPDATE
     */
    public void setREPL_UPDATE(BigDecimal REPL_UPDATE) {
        this.REPL_UPDATE = REPL_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.REPL_DELETE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.REPL_DELETE
     */
    public BigDecimal getREPL_DELETE() {
        return REPL_DELETE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.REPL_DELETE
     *
     * @param REPL_DELETE the value for SYNC_ENTITY_PARAMETERS.REPL_DELETE
     */
    public void setREPL_DELETE(BigDecimal REPL_DELETE) {
        this.REPL_DELETE = REPL_DELETE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.POP_INSERT
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.POP_INSERT
     */
    public BigDecimal getPOP_INSERT() {
        return POP_INSERT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.POP_INSERT
     *
     * @param POP_INSERT the value for SYNC_ENTITY_PARAMETERS.POP_INSERT
     */
    public void setPOP_INSERT(BigDecimal POP_INSERT) {
        this.POP_INSERT = POP_INSERT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.POP_UPDATE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.POP_UPDATE
     */
    public BigDecimal getPOP_UPDATE() {
        return POP_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.POP_UPDATE
     *
     * @param POP_UPDATE the value for SYNC_ENTITY_PARAMETERS.POP_UPDATE
     */
    public void setPOP_UPDATE(BigDecimal POP_UPDATE) {
        this.POP_UPDATE = POP_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.POP_DELETE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.POP_DELETE
     */
    public BigDecimal getPOP_DELETE() {
        return POP_DELETE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.POP_DELETE
     *
     * @param POP_DELETE the value for SYNC_ENTITY_PARAMETERS.POP_DELETE
     */
    public void setPOP_DELETE(BigDecimal POP_DELETE) {
        this.POP_DELETE = POP_DELETE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.TIME_OUT
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.TIME_OUT
     */
    public BigDecimal getTIME_OUT() {
        return TIME_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.TIME_OUT
     *
     * @param TIME_OUT the value for SYNC_ENTITY_PARAMETERS.TIME_OUT
     */
    public void setTIME_OUT(BigDecimal TIME_OUT) {
        this.TIME_OUT = TIME_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ADD_DATE1
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ADD_DATE1
     */
    public Date getADD_DATE1() {
        return ADD_DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ADD_DATE1
     *
     * @param ADD_DATE1 the value for SYNC_ENTITY_PARAMETERS.ADD_DATE1
     */
    public void setADD_DATE1(Date ADD_DATE1) {
        this.ADD_DATE1 = ADD_DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ADD_NUMBER1
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ADD_NUMBER1
     */
    public BigDecimal getADD_NUMBER1() {
        return ADD_NUMBER1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ADD_NUMBER1
     *
     * @param ADD_NUMBER1 the value for SYNC_ENTITY_PARAMETERS.ADD_NUMBER1
     */
    public void setADD_NUMBER1(BigDecimal ADD_NUMBER1) {
        this.ADD_NUMBER1 = ADD_NUMBER1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ADD_STRING1
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ADD_STRING1
     */
    public String getADD_STRING1() {
        return ADD_STRING1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ADD_STRING1
     *
     * @param ADD_STRING1 the value for SYNC_ENTITY_PARAMETERS.ADD_STRING1
     */
    public void setADD_STRING1(String ADD_STRING1) {
        this.ADD_STRING1 = ADD_STRING1 == null ? null : ADD_STRING1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.RELATIVE_FLAG
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.RELATIVE_FLAG
     */
    public BigDecimal getRELATIVE_FLAG() {
        return RELATIVE_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.RELATIVE_FLAG
     *
     * @param RELATIVE_FLAG the value for SYNC_ENTITY_PARAMETERS.RELATIVE_FLAG
     */
    public void setRELATIVE_FLAG(BigDecimal RELATIVE_FLAG) {
        this.RELATIVE_FLAG = RELATIVE_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.INT_LEVEL
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.INT_LEVEL
     */
    public String getINT_LEVEL() {
        return INT_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.INT_LEVEL
     *
     * @param INT_LEVEL the value for SYNC_ENTITY_PARAMETERS.INT_LEVEL
     */
    public void setINT_LEVEL(String INT_LEVEL) {
        this.INT_LEVEL = INT_LEVEL == null ? null : INT_LEVEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.EXT_SP_NAME
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.EXT_SP_NAME
     */
    public String getEXT_SP_NAME() {
        return EXT_SP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.EXT_SP_NAME
     *
     * @param EXT_SP_NAME the value for SYNC_ENTITY_PARAMETERS.EXT_SP_NAME
     */
    public void setEXT_SP_NAME(String EXT_SP_NAME) {
        this.EXT_SP_NAME = EXT_SP_NAME == null ? null : EXT_SP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ENTITY_ORDER
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ENTITY_ORDER
     */
    public BigDecimal getENTITY_ORDER() {
        return ENTITY_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ENTITY_ORDER
     *
     * @param ENTITY_ORDER the value for SYNC_ENTITY_PARAMETERS.ENTITY_ORDER
     */
    public void setENTITY_ORDER(BigDecimal ENTITY_ORDER) {
        this.ENTITY_ORDER = ENTITY_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ERR_PROMPT
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ERR_PROMPT
     */
    public BigDecimal getERR_PROMPT() {
        return ERR_PROMPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ERR_PROMPT
     *
     * @param ERR_PROMPT the value for SYNC_ENTITY_PARAMETERS.ERR_PROMPT
     */
    public void setERR_PROMPT(BigDecimal ERR_PROMPT) {
        this.ERR_PROMPT = ERR_PROMPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.ERR_TYPE
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.ERR_TYPE
     */
    public BigDecimal getERR_TYPE() {
        return ERR_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.ERR_TYPE
     *
     * @param ERR_TYPE the value for SYNC_ENTITY_PARAMETERS.ERR_TYPE
     */
    public void setERR_TYPE(BigDecimal ERR_TYPE) {
        this.ERR_TYPE = ERR_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY_PARAMETERS.UPD_CNT_FLAG
     *
     * @return the value of SYNC_ENTITY_PARAMETERS.UPD_CNT_FLAG
     */
    public BigDecimal getUPD_CNT_FLAG() {
        return UPD_CNT_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY_PARAMETERS.UPD_CNT_FLAG
     *
     * @param UPD_CNT_FLAG the value for SYNC_ENTITY_PARAMETERS.UPD_CNT_FLAG
     */
    public void setUPD_CNT_FLAG(BigDecimal UPD_CNT_FLAG) {
        this.UPD_CNT_FLAG = UPD_CNT_FLAG;
    }
}