package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class SYNC_BRANCHVO extends SYNC_BRANCHVOKey {
    /**
     * This field corresponds to the database column SYNC_BRANCH.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column SYNC_BRANCH.BR_TYPE
     */
    private String BR_TYPE;

    /**
     * This field corresponds to the database column SYNC_BRANCH.EMAIL1
     */
    private String EMAIL1;

    /**
     * This field corresponds to the database column SYNC_BRANCH.EMAIL2
     */
    private String EMAIL2;

    /**
     * This field corresponds to the database column SYNC_BRANCH.EMAIL3
     */
    private String EMAIL3;

    /**
     * This field corresponds to the database column SYNC_BRANCH.EMAIL4
     */
    private String EMAIL4;

    /**
     * This field corresponds to the database column SYNC_BRANCH.EMAIL5
     */
    private String EMAIL5;

    /**
     * This field corresponds to the database column SYNC_BRANCH.MESSAGE1
     */
    private String MESSAGE1;

    /**
     * This field corresponds to the database column SYNC_BRANCH.SUBJECT
     */
    private String SUBJECT;

    /**
     * This field corresponds to the database column SYNC_BRANCH.IP_ADDRESS
     */
    private String IP_ADDRESS;

    /**
     * This field corresponds to the database column SYNC_BRANCH.SERVICE_NAME
     */
    private String SERVICE_NAME;

    /**
     * This field corresponds to the database column SYNC_BRANCH.RDBMS_TYPE
     */
    private BigDecimal RDBMS_TYPE;

    /**
     * This field corresponds to the database column SYNC_BRANCH.EXT_RDBMS
     */
    private BigDecimal EXT_RDBMS;

    /**
     * This field corresponds to the database column SYNC_BRANCH.SB_IND
     */
    private String SB_IND;

    /**
     * This field corresponds to the database column SYNC_BRANCH.BR_STATUS
     */
    private BigDecimal BR_STATUS;

    /**
     * This field corresponds to the database column SYNC_BRANCH.SUSPEND_BR
     */
    private BigDecimal SUSPEND_BR;

    /**
     * This field corresponds to the database column SYNC_BRANCH.BYPASS_BR_STATUS
     */
    private BigDecimal BYPASS_BR_STATUS;

    /**
     * This field corresponds to the database column SYNC_BRANCH.ORDER_FLAG
     */
    private String ORDER_FLAG;

    /**
     * This field corresponds to the database column SYNC_BRANCH.DBLINK_NAME
     */
    private String DBLINK_NAME;

    /**
     * This field corresponds to the database column SYNC_BRANCH.ERR_SUBJECT
     */
    private String ERR_SUBJECT;

    /**
     * This field corresponds to the database column SYNC_BRANCH.ERR_MESSAGE
     */
    private String ERR_MESSAGE;

    /**
     * This field corresponds to the database column SYNC_BRANCH.VR_MODE
     */
    private BigDecimal VR_MODE;

    /**
     * This field corresponds to the database column SYNC_BRANCH.GENERATE_DML
     */
    private BigDecimal GENERATE_DML;

    /**
     * This field corresponds to the database column SYNC_BRANCH.VR_HOST_BR
     */
    private BigDecimal VR_HOST_BR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.DESCRIPTION
     *
     * @return the value of SYNC_BRANCH.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.DESCRIPTION
     *
     * @param DESCRIPTION the value for SYNC_BRANCH.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.BR_TYPE
     *
     * @return the value of SYNC_BRANCH.BR_TYPE
     */
    public String getBR_TYPE() {
        return BR_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.BR_TYPE
     *
     * @param BR_TYPE the value for SYNC_BRANCH.BR_TYPE
     */
    public void setBR_TYPE(String BR_TYPE) {
        this.BR_TYPE = BR_TYPE == null ? null : BR_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.EMAIL1
     *
     * @return the value of SYNC_BRANCH.EMAIL1
     */
    public String getEMAIL1() {
        return EMAIL1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.EMAIL1
     *
     * @param EMAIL1 the value for SYNC_BRANCH.EMAIL1
     */
    public void setEMAIL1(String EMAIL1) {
        this.EMAIL1 = EMAIL1 == null ? null : EMAIL1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.EMAIL2
     *
     * @return the value of SYNC_BRANCH.EMAIL2
     */
    public String getEMAIL2() {
        return EMAIL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.EMAIL2
     *
     * @param EMAIL2 the value for SYNC_BRANCH.EMAIL2
     */
    public void setEMAIL2(String EMAIL2) {
        this.EMAIL2 = EMAIL2 == null ? null : EMAIL2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.EMAIL3
     *
     * @return the value of SYNC_BRANCH.EMAIL3
     */
    public String getEMAIL3() {
        return EMAIL3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.EMAIL3
     *
     * @param EMAIL3 the value for SYNC_BRANCH.EMAIL3
     */
    public void setEMAIL3(String EMAIL3) {
        this.EMAIL3 = EMAIL3 == null ? null : EMAIL3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.EMAIL4
     *
     * @return the value of SYNC_BRANCH.EMAIL4
     */
    public String getEMAIL4() {
        return EMAIL4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.EMAIL4
     *
     * @param EMAIL4 the value for SYNC_BRANCH.EMAIL4
     */
    public void setEMAIL4(String EMAIL4) {
        this.EMAIL4 = EMAIL4 == null ? null : EMAIL4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.EMAIL5
     *
     * @return the value of SYNC_BRANCH.EMAIL5
     */
    public String getEMAIL5() {
        return EMAIL5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.EMAIL5
     *
     * @param EMAIL5 the value for SYNC_BRANCH.EMAIL5
     */
    public void setEMAIL5(String EMAIL5) {
        this.EMAIL5 = EMAIL5 == null ? null : EMAIL5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.MESSAGE1
     *
     * @return the value of SYNC_BRANCH.MESSAGE1
     */
    public String getMESSAGE1() {
        return MESSAGE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.MESSAGE1
     *
     * @param MESSAGE1 the value for SYNC_BRANCH.MESSAGE1
     */
    public void setMESSAGE1(String MESSAGE1) {
        this.MESSAGE1 = MESSAGE1 == null ? null : MESSAGE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.SUBJECT
     *
     * @return the value of SYNC_BRANCH.SUBJECT
     */
    public String getSUBJECT() {
        return SUBJECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.SUBJECT
     *
     * @param SUBJECT the value for SYNC_BRANCH.SUBJECT
     */
    public void setSUBJECT(String SUBJECT) {
        this.SUBJECT = SUBJECT == null ? null : SUBJECT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.IP_ADDRESS
     *
     * @return the value of SYNC_BRANCH.IP_ADDRESS
     */
    public String getIP_ADDRESS() {
        return IP_ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.IP_ADDRESS
     *
     * @param IP_ADDRESS the value for SYNC_BRANCH.IP_ADDRESS
     */
    public void setIP_ADDRESS(String IP_ADDRESS) {
        this.IP_ADDRESS = IP_ADDRESS == null ? null : IP_ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.SERVICE_NAME
     *
     * @return the value of SYNC_BRANCH.SERVICE_NAME
     */
    public String getSERVICE_NAME() {
        return SERVICE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.SERVICE_NAME
     *
     * @param SERVICE_NAME the value for SYNC_BRANCH.SERVICE_NAME
     */
    public void setSERVICE_NAME(String SERVICE_NAME) {
        this.SERVICE_NAME = SERVICE_NAME == null ? null : SERVICE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.RDBMS_TYPE
     *
     * @return the value of SYNC_BRANCH.RDBMS_TYPE
     */
    public BigDecimal getRDBMS_TYPE() {
        return RDBMS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.RDBMS_TYPE
     *
     * @param RDBMS_TYPE the value for SYNC_BRANCH.RDBMS_TYPE
     */
    public void setRDBMS_TYPE(BigDecimal RDBMS_TYPE) {
        this.RDBMS_TYPE = RDBMS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.EXT_RDBMS
     *
     * @return the value of SYNC_BRANCH.EXT_RDBMS
     */
    public BigDecimal getEXT_RDBMS() {
        return EXT_RDBMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.EXT_RDBMS
     *
     * @param EXT_RDBMS the value for SYNC_BRANCH.EXT_RDBMS
     */
    public void setEXT_RDBMS(BigDecimal EXT_RDBMS) {
        this.EXT_RDBMS = EXT_RDBMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.SB_IND
     *
     * @return the value of SYNC_BRANCH.SB_IND
     */
    public String getSB_IND() {
        return SB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.SB_IND
     *
     * @param SB_IND the value for SYNC_BRANCH.SB_IND
     */
    public void setSB_IND(String SB_IND) {
        this.SB_IND = SB_IND == null ? null : SB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.BR_STATUS
     *
     * @return the value of SYNC_BRANCH.BR_STATUS
     */
    public BigDecimal getBR_STATUS() {
        return BR_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.BR_STATUS
     *
     * @param BR_STATUS the value for SYNC_BRANCH.BR_STATUS
     */
    public void setBR_STATUS(BigDecimal BR_STATUS) {
        this.BR_STATUS = BR_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.SUSPEND_BR
     *
     * @return the value of SYNC_BRANCH.SUSPEND_BR
     */
    public BigDecimal getSUSPEND_BR() {
        return SUSPEND_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.SUSPEND_BR
     *
     * @param SUSPEND_BR the value for SYNC_BRANCH.SUSPEND_BR
     */
    public void setSUSPEND_BR(BigDecimal SUSPEND_BR) {
        this.SUSPEND_BR = SUSPEND_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.BYPASS_BR_STATUS
     *
     * @return the value of SYNC_BRANCH.BYPASS_BR_STATUS
     */
    public BigDecimal getBYPASS_BR_STATUS() {
        return BYPASS_BR_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.BYPASS_BR_STATUS
     *
     * @param BYPASS_BR_STATUS the value for SYNC_BRANCH.BYPASS_BR_STATUS
     */
    public void setBYPASS_BR_STATUS(BigDecimal BYPASS_BR_STATUS) {
        this.BYPASS_BR_STATUS = BYPASS_BR_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.ORDER_FLAG
     *
     * @return the value of SYNC_BRANCH.ORDER_FLAG
     */
    public String getORDER_FLAG() {
        return ORDER_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.ORDER_FLAG
     *
     * @param ORDER_FLAG the value for SYNC_BRANCH.ORDER_FLAG
     */
    public void setORDER_FLAG(String ORDER_FLAG) {
        this.ORDER_FLAG = ORDER_FLAG == null ? null : ORDER_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.DBLINK_NAME
     *
     * @return the value of SYNC_BRANCH.DBLINK_NAME
     */
    public String getDBLINK_NAME() {
        return DBLINK_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.DBLINK_NAME
     *
     * @param DBLINK_NAME the value for SYNC_BRANCH.DBLINK_NAME
     */
    public void setDBLINK_NAME(String DBLINK_NAME) {
        this.DBLINK_NAME = DBLINK_NAME == null ? null : DBLINK_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.ERR_SUBJECT
     *
     * @return the value of SYNC_BRANCH.ERR_SUBJECT
     */
    public String getERR_SUBJECT() {
        return ERR_SUBJECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.ERR_SUBJECT
     *
     * @param ERR_SUBJECT the value for SYNC_BRANCH.ERR_SUBJECT
     */
    public void setERR_SUBJECT(String ERR_SUBJECT) {
        this.ERR_SUBJECT = ERR_SUBJECT == null ? null : ERR_SUBJECT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.ERR_MESSAGE
     *
     * @return the value of SYNC_BRANCH.ERR_MESSAGE
     */
    public String getERR_MESSAGE() {
        return ERR_MESSAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.ERR_MESSAGE
     *
     * @param ERR_MESSAGE the value for SYNC_BRANCH.ERR_MESSAGE
     */
    public void setERR_MESSAGE(String ERR_MESSAGE) {
        this.ERR_MESSAGE = ERR_MESSAGE == null ? null : ERR_MESSAGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.VR_MODE
     *
     * @return the value of SYNC_BRANCH.VR_MODE
     */
    public BigDecimal getVR_MODE() {
        return VR_MODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.VR_MODE
     *
     * @param VR_MODE the value for SYNC_BRANCH.VR_MODE
     */
    public void setVR_MODE(BigDecimal VR_MODE) {
        this.VR_MODE = VR_MODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.GENERATE_DML
     *
     * @return the value of SYNC_BRANCH.GENERATE_DML
     */
    public BigDecimal getGENERATE_DML() {
        return GENERATE_DML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.GENERATE_DML
     *
     * @param GENERATE_DML the value for SYNC_BRANCH.GENERATE_DML
     */
    public void setGENERATE_DML(BigDecimal GENERATE_DML) {
        this.GENERATE_DML = GENERATE_DML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.VR_HOST_BR
     *
     * @return the value of SYNC_BRANCH.VR_HOST_BR
     */
    public BigDecimal getVR_HOST_BR() {
        return VR_HOST_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.VR_HOST_BR
     *
     * @param VR_HOST_BR the value for SYNC_BRANCH.VR_HOST_BR
     */
    public void setVR_HOST_BR(BigDecimal VR_HOST_BR) {
        this.VR_HOST_BR = VR_HOST_BR;
    }
}