package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class SYNC_COL_MAPPINGVO extends SYNC_COL_MAPPINGVOKey {
    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.FROM_COL
     */
    private String FROM_COL;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.FROM_LABEL
     */
    private String FROM_LABEL;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.TO_COL
     */
    private String TO_COL;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.TO_LABEL
     */
    private String TO_LABEL;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.IN_OUT
     */
    private String IN_OUT;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.COL_TYPE
     */
    private String COL_TYPE;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.ACTION
     */
    private String ACTION;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.COL_DEFAULT
     */
    private String COL_DEFAULT;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.API_CODE
     */
    private BigDecimal API_CODE;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.VALUE_SUCCESS
     */
    private String VALUE_SUCCESS;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.VALUE_ERROR
     */
    private String VALUE_ERROR;

    /**
     * This field corresponds to the database column SYNC_COL_MAPPING.MSG_TYPE
     */
    private String MSG_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.FROM_COL
     *
     * @return the value of SYNC_COL_MAPPING.FROM_COL
     */
    public String getFROM_COL() {
        return FROM_COL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.FROM_COL
     *
     * @param FROM_COL the value for SYNC_COL_MAPPING.FROM_COL
     */
    public void setFROM_COL(String FROM_COL) {
        this.FROM_COL = FROM_COL == null ? null : FROM_COL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.FROM_LABEL
     *
     * @return the value of SYNC_COL_MAPPING.FROM_LABEL
     */
    public String getFROM_LABEL() {
        return FROM_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.FROM_LABEL
     *
     * @param FROM_LABEL the value for SYNC_COL_MAPPING.FROM_LABEL
     */
    public void setFROM_LABEL(String FROM_LABEL) {
        this.FROM_LABEL = FROM_LABEL == null ? null : FROM_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.TO_COL
     *
     * @return the value of SYNC_COL_MAPPING.TO_COL
     */
    public String getTO_COL() {
        return TO_COL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.TO_COL
     *
     * @param TO_COL the value for SYNC_COL_MAPPING.TO_COL
     */
    public void setTO_COL(String TO_COL) {
        this.TO_COL = TO_COL == null ? null : TO_COL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.TO_LABEL
     *
     * @return the value of SYNC_COL_MAPPING.TO_LABEL
     */
    public String getTO_LABEL() {
        return TO_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.TO_LABEL
     *
     * @param TO_LABEL the value for SYNC_COL_MAPPING.TO_LABEL
     */
    public void setTO_LABEL(String TO_LABEL) {
        this.TO_LABEL = TO_LABEL == null ? null : TO_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.IN_OUT
     *
     * @return the value of SYNC_COL_MAPPING.IN_OUT
     */
    public String getIN_OUT() {
        return IN_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.IN_OUT
     *
     * @param IN_OUT the value for SYNC_COL_MAPPING.IN_OUT
     */
    public void setIN_OUT(String IN_OUT) {
        this.IN_OUT = IN_OUT == null ? null : IN_OUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.COL_TYPE
     *
     * @return the value of SYNC_COL_MAPPING.COL_TYPE
     */
    public String getCOL_TYPE() {
        return COL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.COL_TYPE
     *
     * @param COL_TYPE the value for SYNC_COL_MAPPING.COL_TYPE
     */
    public void setCOL_TYPE(String COL_TYPE) {
        this.COL_TYPE = COL_TYPE == null ? null : COL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.ACTION
     *
     * @return the value of SYNC_COL_MAPPING.ACTION
     */
    public String getACTION() {
        return ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.ACTION
     *
     * @param ACTION the value for SYNC_COL_MAPPING.ACTION
     */
    public void setACTION(String ACTION) {
        this.ACTION = ACTION == null ? null : ACTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.COL_DEFAULT
     *
     * @return the value of SYNC_COL_MAPPING.COL_DEFAULT
     */
    public String getCOL_DEFAULT() {
        return COL_DEFAULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.COL_DEFAULT
     *
     * @param COL_DEFAULT the value for SYNC_COL_MAPPING.COL_DEFAULT
     */
    public void setCOL_DEFAULT(String COL_DEFAULT) {
        this.COL_DEFAULT = COL_DEFAULT == null ? null : COL_DEFAULT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.API_CODE
     *
     * @return the value of SYNC_COL_MAPPING.API_CODE
     */
    public BigDecimal getAPI_CODE() {
        return API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.API_CODE
     *
     * @param API_CODE the value for SYNC_COL_MAPPING.API_CODE
     */
    public void setAPI_CODE(BigDecimal API_CODE) {
        this.API_CODE = API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.VALUE_SUCCESS
     *
     * @return the value of SYNC_COL_MAPPING.VALUE_SUCCESS
     */
    public String getVALUE_SUCCESS() {
        return VALUE_SUCCESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.VALUE_SUCCESS
     *
     * @param VALUE_SUCCESS the value for SYNC_COL_MAPPING.VALUE_SUCCESS
     */
    public void setVALUE_SUCCESS(String VALUE_SUCCESS) {
        this.VALUE_SUCCESS = VALUE_SUCCESS == null ? null : VALUE_SUCCESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.VALUE_ERROR
     *
     * @return the value of SYNC_COL_MAPPING.VALUE_ERROR
     */
    public String getVALUE_ERROR() {
        return VALUE_ERROR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.VALUE_ERROR
     *
     * @param VALUE_ERROR the value for SYNC_COL_MAPPING.VALUE_ERROR
     */
    public void setVALUE_ERROR(String VALUE_ERROR) {
        this.VALUE_ERROR = VALUE_ERROR == null ? null : VALUE_ERROR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_COL_MAPPING.MSG_TYPE
     *
     * @return the value of SYNC_COL_MAPPING.MSG_TYPE
     */
    public String getMSG_TYPE() {
        return MSG_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_COL_MAPPING.MSG_TYPE
     *
     * @param MSG_TYPE the value for SYNC_COL_MAPPING.MSG_TYPE
     */
    public void setMSG_TYPE(String MSG_TYPE) {
        this.MSG_TYPE = MSG_TYPE == null ? null : MSG_TYPE.trim();
    }
}