package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYNC_ENTITYVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYNC_ENTITY.ENTITY_CODE
     */
    private BigDecimal ENTITY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ENTITY.ENTITY_CODE
     *
     * @return the value of SYNC_ENTITY.ENTITY_CODE
     */
    public BigDecimal getENTITY_CODE() {
        return ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ENTITY.ENTITY_CODE
     *
     * @param ENTITY_CODE the value for SYNC_ENTITY.ENTITY_CODE
     */
    public void setENTITY_CODE(BigDecimal ENTITY_CODE) {
        this.ENTITY_CODE = ENTITY_CODE;
    }
}