package com.path.dbmaps.vo;

public class SYNC_FIXED_MAPPINGVO extends SYNC_FIXED_MAPPINGVOKey {
    /**
     * This field corresponds to the database column SYNC_FIXED_MAPPING.IMAL_VALUE
     */
    private String IMAL_VALUE;

    /**
     * This field corresponds to the database column SYNC_FIXED_MAPPING.EXT_SYS_VALUE
     */
    private String EXT_SYS_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_FIXED_MAPPING.IMAL_VALUE
     *
     * @return the value of SYNC_FIXED_MAPPING.IMAL_VALUE
     */
    public String getIMAL_VALUE() {
        return IMAL_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_FIXED_MAPPING.IMAL_VALUE
     *
     * @param IMAL_VALUE the value for SYNC_FIXED_MAPPING.IMAL_VALUE
     */
    public void setIMAL_VALUE(String IMAL_VALUE) {
        this.IMAL_VALUE = IMAL_VALUE == null ? null : IMAL_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_FIXED_MAPPING.EXT_SYS_VALUE
     *
     * @return the value of SYNC_FIXED_MAPPING.EXT_SYS_VALUE
     */
    public String getEXT_SYS_VALUE() {
        return EXT_SYS_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_FIXED_MAPPING.EXT_SYS_VALUE
     *
     * @param EXT_SYS_VALUE the value for SYNC_FIXED_MAPPING.EXT_SYS_VALUE
     */
    public void setEXT_SYS_VALUE(String EXT_SYS_VALUE) {
        this.EXT_SYS_VALUE = EXT_SYS_VALUE == null ? null : EXT_SYS_VALUE.trim();
    }
}