package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYNC_ACTIONSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYNC_ACTIONS.ACTION
     */
    private String ACTION;

    /**
     * This field corresponds to the database column SYNC_ACTIONS.BR_CODE
     */
    private BigDecimal BR_CODE;

    /**
     * This field corresponds to the database column SYNC_ACTIONS.PROCESS
     */
    private String PROCESS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ACTIONS.ACTION
     *
     * @return the value of SYNC_ACTIONS.ACTION
     */
    public String getACTION() {
        return ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ACTIONS.ACTION
     *
     * @param ACTION the value for SYNC_ACTIONS.ACTION
     */
    public void setACTION(String ACTION) {
        this.ACTION = ACTION == null ? null : ACTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ACTIONS.BR_CODE
     *
     * @return the value of SYNC_ACTIONS.BR_CODE
     */
    public BigDecimal getBR_CODE() {
        return BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ACTIONS.BR_CODE
     *
     * @param BR_CODE the value for SYNC_ACTIONS.BR_CODE
     */
    public void setBR_CODE(BigDecimal BR_CODE) {
        this.BR_CODE = BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ACTIONS.PROCESS
     *
     * @return the value of SYNC_ACTIONS.PROCESS
     */
    public String getPROCESS() {
        return PROCESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ACTIONS.PROCESS
     *
     * @param PROCESS the value for SYNC_ACTIONS.PROCESS
     */
    public void setPROCESS(String PROCESS) {
        this.PROCESS = PROCESS == null ? null : PROCESS.trim();
    }
}