package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class SYNC_INT_LEVELSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.COLUMN_NAME
     */
    private String COLUMN_NAME;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.DWO_NAME
     */
    private String DWO_NAME;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.WINDOW_REFERENCE
     */
    private String WINDOW_REFERENCE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.APP_NAME
     *
     * @return the value of SYNC_INT_LEVELS.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.APP_NAME
     *
     * @param APP_NAME the value for SYNC_INT_LEVELS.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.COLUMN_NAME
     *
     * @return the value of SYNC_INT_LEVELS.COLUMN_NAME
     */
    public String getCOLUMN_NAME() {
        return COLUMN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.COLUMN_NAME
     *
     * @param COLUMN_NAME the value for SYNC_INT_LEVELS.COLUMN_NAME
     */
    public void setCOLUMN_NAME(String COLUMN_NAME) {
        this.COLUMN_NAME = COLUMN_NAME == null ? null : COLUMN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.DWO_NAME
     *
     * @return the value of SYNC_INT_LEVELS.DWO_NAME
     */
    public String getDWO_NAME() {
        return DWO_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.DWO_NAME
     *
     * @param DWO_NAME the value for SYNC_INT_LEVELS.DWO_NAME
     */
    public void setDWO_NAME(String DWO_NAME) {
        this.DWO_NAME = DWO_NAME == null ? null : DWO_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.WINDOW_REFERENCE
     *
     * @return the value of SYNC_INT_LEVELS.WINDOW_REFERENCE
     */
    public String getWINDOW_REFERENCE() {
        return WINDOW_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.WINDOW_REFERENCE
     *
     * @param WINDOW_REFERENCE the value for SYNC_INT_LEVELS.WINDOW_REFERENCE
     */
    public void setWINDOW_REFERENCE(String WINDOW_REFERENCE) {
        this.WINDOW_REFERENCE = WINDOW_REFERENCE == null ? null : WINDOW_REFERENCE.trim();
    }
}