package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class SYNC_CONNECTIONVO extends SYNC_CONNECTIONVOKey {
    /**
     * This field corresponds to the database column SYNC_CONNECTION.TIMER
     */
    private BigDecimal TIMER;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.RECONNECT
     */
    private BigDecimal RECONNECT;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.ACTION_TYPE
     */
    private BigDecimal ACTION_TYPE;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.ACTION_DATETIME
     */
    private Date ACTION_DATETIME;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.PERIOD
     */
    private BigDecimal PERIOD;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.PERIOD_TYPE
     */
    private String PERIOD_TYPE;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.PERIOD_DAY
     */
    private BigDecimal PERIOD_DAY;

    /**
     * This field corresponds to the database column SYNC_CONNECTION.LAST_ID
     */
    private BigDecimal LAST_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.TIMER
     *
     * @return the value of SYNC_CONNECTION.TIMER
     */
    public BigDecimal getTIMER() {
        return TIMER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.TIMER
     *
     * @param TIMER the value for SYNC_CONNECTION.TIMER
     */
    public void setTIMER(BigDecimal TIMER) {
        this.TIMER = TIMER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.STATUS
     *
     * @return the value of SYNC_CONNECTION.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.STATUS
     *
     * @param STATUS the value for SYNC_CONNECTION.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.RECONNECT
     *
     * @return the value of SYNC_CONNECTION.RECONNECT
     */
    public BigDecimal getRECONNECT() {
        return RECONNECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.RECONNECT
     *
     * @param RECONNECT the value for SYNC_CONNECTION.RECONNECT
     */
    public void setRECONNECT(BigDecimal RECONNECT) {
        this.RECONNECT = RECONNECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.ACTION_TYPE
     *
     * @return the value of SYNC_CONNECTION.ACTION_TYPE
     */
    public BigDecimal getACTION_TYPE() {
        return ACTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.ACTION_TYPE
     *
     * @param ACTION_TYPE the value for SYNC_CONNECTION.ACTION_TYPE
     */
    public void setACTION_TYPE(BigDecimal ACTION_TYPE) {
        this.ACTION_TYPE = ACTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.ACTION_DATETIME
     *
     * @return the value of SYNC_CONNECTION.ACTION_DATETIME
     */
    public Date getACTION_DATETIME() {
        return ACTION_DATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.ACTION_DATETIME
     *
     * @param ACTION_DATETIME the value for SYNC_CONNECTION.ACTION_DATETIME
     */
    public void setACTION_DATETIME(Date ACTION_DATETIME) {
        this.ACTION_DATETIME = ACTION_DATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.PERIOD
     *
     * @return the value of SYNC_CONNECTION.PERIOD
     */
    public BigDecimal getPERIOD() {
        return PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.PERIOD
     *
     * @param PERIOD the value for SYNC_CONNECTION.PERIOD
     */
    public void setPERIOD(BigDecimal PERIOD) {
        this.PERIOD = PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.PERIOD_TYPE
     *
     * @return the value of SYNC_CONNECTION.PERIOD_TYPE
     */
    public String getPERIOD_TYPE() {
        return PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.PERIOD_TYPE
     *
     * @param PERIOD_TYPE the value for SYNC_CONNECTION.PERIOD_TYPE
     */
    public void setPERIOD_TYPE(String PERIOD_TYPE) {
        this.PERIOD_TYPE = PERIOD_TYPE == null ? null : PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.PERIOD_DAY
     *
     * @return the value of SYNC_CONNECTION.PERIOD_DAY
     */
    public BigDecimal getPERIOD_DAY() {
        return PERIOD_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.PERIOD_DAY
     *
     * @param PERIOD_DAY the value for SYNC_CONNECTION.PERIOD_DAY
     */
    public void setPERIOD_DAY(BigDecimal PERIOD_DAY) {
        this.PERIOD_DAY = PERIOD_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_CONNECTION.LAST_ID
     *
     * @return the value of SYNC_CONNECTION.LAST_ID
     */
    public BigDecimal getLAST_ID() {
        return LAST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_CONNECTION.LAST_ID
     *
     * @param LAST_ID the value for SYNC_CONNECTION.LAST_ID
     */
    public void setLAST_ID(BigDecimal LAST_ID) {
        this.LAST_ID = LAST_ID;
    }
}