package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class SYNC_ACTIONSVO extends SYNC_ACTIONSVOKey {
    /**
     * This field corresponds to the database column SYNC_ACTIONS.TERMINAL
     */
    private String TERMINAL;

    /**
     * This field corresponds to the database column SYNC_ACTIONS.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column SYNC_ACTIONS.SYNC_ID
     */
    private BigDecimal SYNC_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ACTIONS.TERMINAL
     *
     * @return the value of SYNC_ACTIONS.TERMINAL
     */
    public String getTERMINAL() {
        return TERMINAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ACTIONS.TERMINAL
     *
     * @param TERMINAL the value for SYNC_ACTIONS.TERMINAL
     */
    public void setTERMINAL(String TERMINAL) {
        this.TERMINAL = TERMINAL == null ? null : TERMINAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ACTIONS.USER_ID
     *
     * @return the value of SYNC_ACTIONS.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ACTIONS.USER_ID
     *
     * @param USER_ID the value for SYNC_ACTIONS.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_ACTIONS.SYNC_ID
     *
     * @return the value of SYNC_ACTIONS.SYNC_ID
     */
    public BigDecimal getSYNC_ID() {
        return SYNC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_ACTIONS.SYNC_ID
     *
     * @param SYNC_ID the value for SYNC_ACTIONS.SYNC_ID
     */
    public void setSYNC_ID(BigDecimal SYNC_ID) {
        this.SYNC_ID = SYNC_ID;
    }
}