package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYNC_BRANCHVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYNC_BRANCH.BR_CODE
     */
    private BigDecimal BR_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_BRANCH.BR_CODE
     *
     * @return the value of SYNC_BRANCH.BR_CODE
     */
    public BigDecimal getBR_CODE() {
        return BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_BRANCH.BR_CODE
     *
     * @param BR_CODE the value for SYNC_BRANCH.BR_CODE
     */
    public void setBR_CODE(BigDecimal BR_CODE) {
        this.BR_CODE = BR_CODE;
    }
}