package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYNC_FIXED_MAPPINGVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYNC_FIXED_MAPPING.BR_CODE
     */
    private BigDecimal BR_CODE;

    /**
     * This field corresponds to the database column SYNC_FIXED_MAPPING.COL_NBR
     */
    private BigDecimal COL_NBR;

    /**
     * This field corresponds to the database column SYNC_FIXED_MAPPING.ENTITY_CODE
     */
    private BigDecimal ENTITY_CODE;

    /**
     * This field corresponds to the database column SYNC_FIXED_MAPPING.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_FIXED_MAPPING.BR_CODE
     *
     * @return the value of SYNC_FIXED_MAPPING.BR_CODE
     */
    public BigDecimal getBR_CODE() {
        return BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_FIXED_MAPPING.BR_CODE
     *
     * @param BR_CODE the value for SYNC_FIXED_MAPPING.BR_CODE
     */
    public void setBR_CODE(BigDecimal BR_CODE) {
        this.BR_CODE = BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_FIXED_MAPPING.COL_NBR
     *
     * @return the value of SYNC_FIXED_MAPPING.COL_NBR
     */
    public BigDecimal getCOL_NBR() {
        return COL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_FIXED_MAPPING.COL_NBR
     *
     * @param COL_NBR the value for SYNC_FIXED_MAPPING.COL_NBR
     */
    public void setCOL_NBR(BigDecimal COL_NBR) {
        this.COL_NBR = COL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_FIXED_MAPPING.ENTITY_CODE
     *
     * @return the value of SYNC_FIXED_MAPPING.ENTITY_CODE
     */
    public BigDecimal getENTITY_CODE() {
        return ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_FIXED_MAPPING.ENTITY_CODE
     *
     * @param ENTITY_CODE the value for SYNC_FIXED_MAPPING.ENTITY_CODE
     */
    public void setENTITY_CODE(BigDecimal ENTITY_CODE) {
        this.ENTITY_CODE = ENTITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_FIXED_MAPPING.LINE_NBR
     *
     * @return the value of SYNC_FIXED_MAPPING.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_FIXED_MAPPING.LINE_NBR
     *
     * @param LINE_NBR the value for SYNC_FIXED_MAPPING.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }
}