package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class SYNC_INT_LEVELSVO extends SYNC_INT_LEVELSVOKey {
    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.WINDOW_NAME
     */
    private String WINDOW_NAME;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.WINDOW_LABEL
     */
    private String WINDOW_LABEL;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.DWO_LABEL
     */
    private String DWO_LABEL;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.COLUMN_LABEL
     */
    private String COLUMN_LABEL;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.STATUS
     */
    private BigDecimal STATUS;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.INT_LEVEL
     */
    private String INT_LEVEL;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.TIME_OUT
     */
    private BigDecimal TIME_OUT;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.COLUMN_NBR
     */
    private BigDecimal COLUMN_NBR;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.COLUMN_RELATION_NBR
     */
    private BigDecimal COLUMN_RELATION_NBR;

    /**
     * This field corresponds to the database column SYNC_INT_LEVELS.ALLOW_PROMPT
     */
    private String ALLOW_PROMPT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.WINDOW_NAME
     *
     * @return the value of SYNC_INT_LEVELS.WINDOW_NAME
     */
    public String getWINDOW_NAME() {
        return WINDOW_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.WINDOW_NAME
     *
     * @param WINDOW_NAME the value for SYNC_INT_LEVELS.WINDOW_NAME
     */
    public void setWINDOW_NAME(String WINDOW_NAME) {
        this.WINDOW_NAME = WINDOW_NAME == null ? null : WINDOW_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.WINDOW_LABEL
     *
     * @return the value of SYNC_INT_LEVELS.WINDOW_LABEL
     */
    public String getWINDOW_LABEL() {
        return WINDOW_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.WINDOW_LABEL
     *
     * @param WINDOW_LABEL the value for SYNC_INT_LEVELS.WINDOW_LABEL
     */
    public void setWINDOW_LABEL(String WINDOW_LABEL) {
        this.WINDOW_LABEL = WINDOW_LABEL == null ? null : WINDOW_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.DWO_LABEL
     *
     * @return the value of SYNC_INT_LEVELS.DWO_LABEL
     */
    public String getDWO_LABEL() {
        return DWO_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.DWO_LABEL
     *
     * @param DWO_LABEL the value for SYNC_INT_LEVELS.DWO_LABEL
     */
    public void setDWO_LABEL(String DWO_LABEL) {
        this.DWO_LABEL = DWO_LABEL == null ? null : DWO_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.COLUMN_LABEL
     *
     * @return the value of SYNC_INT_LEVELS.COLUMN_LABEL
     */
    public String getCOLUMN_LABEL() {
        return COLUMN_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.COLUMN_LABEL
     *
     * @param COLUMN_LABEL the value for SYNC_INT_LEVELS.COLUMN_LABEL
     */
    public void setCOLUMN_LABEL(String COLUMN_LABEL) {
        this.COLUMN_LABEL = COLUMN_LABEL == null ? null : COLUMN_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.STATUS
     *
     * @return the value of SYNC_INT_LEVELS.STATUS
     */
    public BigDecimal getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.STATUS
     *
     * @param STATUS the value for SYNC_INT_LEVELS.STATUS
     */
    public void setSTATUS(BigDecimal STATUS) {
        this.STATUS = STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.INT_LEVEL
     *
     * @return the value of SYNC_INT_LEVELS.INT_LEVEL
     */
    public String getINT_LEVEL() {
        return INT_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.INT_LEVEL
     *
     * @param INT_LEVEL the value for SYNC_INT_LEVELS.INT_LEVEL
     */
    public void setINT_LEVEL(String INT_LEVEL) {
        this.INT_LEVEL = INT_LEVEL == null ? null : INT_LEVEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.TIME_OUT
     *
     * @return the value of SYNC_INT_LEVELS.TIME_OUT
     */
    public BigDecimal getTIME_OUT() {
        return TIME_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.TIME_OUT
     *
     * @param TIME_OUT the value for SYNC_INT_LEVELS.TIME_OUT
     */
    public void setTIME_OUT(BigDecimal TIME_OUT) {
        this.TIME_OUT = TIME_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.COLUMN_NBR
     *
     * @return the value of SYNC_INT_LEVELS.COLUMN_NBR
     */
    public BigDecimal getCOLUMN_NBR() {
        return COLUMN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.COLUMN_NBR
     *
     * @param COLUMN_NBR the value for SYNC_INT_LEVELS.COLUMN_NBR
     */
    public void setCOLUMN_NBR(BigDecimal COLUMN_NBR) {
        this.COLUMN_NBR = COLUMN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.COLUMN_RELATION_NBR
     *
     * @return the value of SYNC_INT_LEVELS.COLUMN_RELATION_NBR
     */
    public BigDecimal getCOLUMN_RELATION_NBR() {
        return COLUMN_RELATION_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.COLUMN_RELATION_NBR
     *
     * @param COLUMN_RELATION_NBR the value for SYNC_INT_LEVELS.COLUMN_RELATION_NBR
     */
    public void setCOLUMN_RELATION_NBR(BigDecimal COLUMN_RELATION_NBR) {
        this.COLUMN_RELATION_NBR = COLUMN_RELATION_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_INT_LEVELS.ALLOW_PROMPT
     *
     * @return the value of SYNC_INT_LEVELS.ALLOW_PROMPT
     */
    public String getALLOW_PROMPT() {
        return ALLOW_PROMPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_INT_LEVELS.ALLOW_PROMPT
     *
     * @param ALLOW_PROMPT the value for SYNC_INT_LEVELS.ALLOW_PROMPT
     */
    public void setALLOW_PROMPT(String ALLOW_PROMPT) {
        this.ALLOW_PROMPT = ALLOW_PROMPT == null ? null : ALLOW_PROMPT.trim();
    }
}