package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYS_PARAM_ISO_FLDSVO extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_ISO_FLDS.ID
     */
    private BigDecimal ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ISO_FLDS.LENGTH
     */
    private BigDecimal LENGTH;

    /**
     * This field corresponds to the database column SYS_PARAM_ISO_FLDS.NAME
     */
    private String NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_ISO_FLDS.FIELD_TYPE
     */
    private String FIELD_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ISO_FLDS.ID
     *
     * @return the value of SYS_PARAM_ISO_FLDS.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ISO_FLDS.ID
     *
     * @param ID the value for SYS_PARAM_ISO_FLDS.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ISO_FLDS.LENGTH
     *
     * @return the value of SYS_PARAM_ISO_FLDS.LENGTH
     */
    public BigDecimal getLENGTH() {
        return LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ISO_FLDS.LENGTH
     *
     * @param LENGTH the value for SYS_PARAM_ISO_FLDS.LENGTH
     */
    public void setLENGTH(BigDecimal LENGTH) {
        this.LENGTH = LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ISO_FLDS.NAME
     *
     * @return the value of SYS_PARAM_ISO_FLDS.NAME
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ISO_FLDS.NAME
     *
     * @param NAME the value for SYS_PARAM_ISO_FLDS.NAME
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ISO_FLDS.FIELD_TYPE
     *
     * @return the value of SYS_PARAM_ISO_FLDS.FIELD_TYPE
     */
    public String getFIELD_TYPE() {
        return FIELD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ISO_FLDS.FIELD_TYPE
     *
     * @param FIELD_TYPE the value for SYS_PARAM_ISO_FLDS.FIELD_TYPE
     */
    public void setFIELD_TYPE(String FIELD_TYPE) {
        this.FIELD_TYPE = FIELD_TYPE == null ? null : FIELD_TYPE.trim();
    }
}